impl Handler {
    fn is_list_mutating_command(command: &Command) -> bool {
        matches!(
            command,
            Command::Blmove(_)
                | Command::Blmpop(_)
                | Command::Blpop(_)
                | Command::Brpop(_)
                | Command::Brpoplpush(_)
                | Command::Linsert(_)
                | Command::Lmove(_)
                | Command::Lmpop(_)
                | Command::Lpop(_)
                | Command::Lpush(_)
                | Command::Lpushx(_)
                | Command::Lset(_)
                | Command::Ltrim(_)
                | Command::Rpop(_)
                | Command::Rpoplpush(_)
                | Command::Rpush(_)
                | Command::Rpushx(_)
        )
    }

    fn is_zset_mutating_command(command: &Command) -> bool {
        matches!(
            command,
            Command::Bzmpop(_)
                | Command::Bzpopmax(_)
                | Command::Bzpopmin(_)
                | Command::Zadd(_)
                | Command::Zdiffstore(_)
                | Command::Zincrby(_)
                | Command::Zinterstore(_)
                | Command::Zmpop(_)
                | Command::Zpopmax(_)
                | Command::Zpopmin(_)
                | Command::Zrangestore(_)
                | Command::Zrem(_)
                | Command::Zremrangebylex(_)
                | Command::Zremrangebyrank(_)
                | Command::Zremrangebyscore(_)
                | Command::Zunionstore(_)
        )
    }

    fn is_stream_mutating_command(command: &Command) -> bool {
        matches!(
            command,
            Command::Xadd(_) | Command::Xdel(_) | Command::Xtrim(_)
        )
    }

    fn can_apply_direct(command: &Command) -> bool {
        matches!(
            command,
            Command::Get(_)
                | Command::Mget(_)
                | Command::Type(_)
                | Command::Ttl(_)
                | Command::Pttl(_)
                | Command::ExpireTime(_)
                | Command::PexpireTime(_)
                | Command::Exists(_)
                | Command::Touch(_)
                | Command::Dbsize(_)
                | Command::Keys(_)
                | Command::Scan(_)
                | Command::Scard(_)
                | Command::Sdiff(_)
                | Command::Sinter(_)
                | Command::Sismember(_)
                | Command::Smembers(_)
                | Command::Smismember(_)
                | Command::Srandmember(_)
                | Command::Sscan(_)
                | Command::Sunion(_)
                | Command::Zcard(_)
                | Command::Zcount(_)
                | Command::Zmscore(_)
                | Command::Zrange(_)
                | Command::Zrangebyscore(_)
                | Command::Zrank(_)
                | Command::Zrevrange(_)
                | Command::Zrevrank(_)
                | Command::Zscan(_)
                | Command::Zscore(_)
                | Command::Strlen(_)
                | Command::Lindex(_)
                | Command::Linsert(_)
                | Command::Llen(_)
                | Command::Lmpop(_)
                | Command::Lpos(_)
                | Command::Lrange(_)
                | Command::Lpush(_)
                | Command::Lpushx(_)
                | Command::Lpop(_)
                | Command::Lrem(_)
                | Command::Lset(_)
                | Command::Ltrim(_)
                | Command::Rpop(_)
                | Command::Rpoplpush(_)
                | Command::Rpush(_)
                | Command::Rpushx(_)
                | Command::Set(_)
                | Command::Setex(_)
                | Command::Mset(_)
                | Command::Incr(_)
                | Command::Incrby(_)
                | Command::Decr(_)
                | Command::Decrby(_)
                | Command::Hset(_)
                | Command::Hdel(_)
                | Command::Hincrby(_)
                | Command::HincrbyFloat(_)
                | Command::Hmset(_)
                | Command::FtCreate(_)
                | Command::FtList(_)
                | Command::FtDropIndex(_)
                | Command::FtAlter(_)
                | Command::FtAliasAdd(_)
                | Command::FtAliasUpdate(_)
                | Command::FtAliasDel(_)
                | Command::FtConfig(_)
                | Command::FtInfo(_)
                | Command::FtSearch(_)
                | Command::FtHybrid(_)
                | Command::FtAggregate(_)
                | Command::FtCursor(_)
                | Command::FtProfile(_)
                | Command::FtDict(_)
                | Command::FtSpellCheck(_)
                | Command::FtSug(_)
                | Command::FtSyn(_)
                | Command::FtUnsupported(_)
                | Command::Flushdb(_)
                | Command::Copy(_)
                | Command::Move(_)
                | Command::Sadd(_)
                | Command::Sdiffstore(_)
                | Command::Sinterstore(_)
                | Command::Spop(_)
                | Command::Srem(_)
                | Command::Sunionstore(_)
                | Command::Zadd(_)
                | Command::Zincrby(_)
                | Command::Zrangestore(_)
                | Command::Zrem(_)
                | Command::Zremrangebyrank(_)
                | Command::Zremrangebyscore(_)
        )
    }

    fn can_apply_on_worker(command: &Command) -> bool {
        matches!(
            command,
            Command::Get(_)
                | Command::Mget(_)
                | Command::Type(_)
                | Command::Ttl(_)
                | Command::Pttl(_)
                | Command::ExpireTime(_)
                | Command::PexpireTime(_)
                | Command::Exists(_)
                | Command::Strlen(_)
                | Command::Dbsize(_)
                | Command::Flushdb(_)
                | Command::Keys(_)
                | Command::Scan(_)
                | Command::Lindex(_)
                | Command::Linsert(_)
                | Command::Llen(_)
                | Command::Lmpop(_)
                | Command::Lpos(_)
                | Command::Lrange(_)
                | Command::Copy(_)
                | Command::Move(_)
                | Command::Scard(_)
                | Command::Sdiff(_)
                | Command::Sdiffstore(_)
                | Command::Sinter(_)
                | Command::Sinterstore(_)
                | Command::Sismember(_)
                | Command::Smembers(_)
                | Command::Smismember(_)
                | Command::Spop(_)
                | Command::Srandmember(_)
                | Command::Sscan(_)
                | Command::Sunion(_)
                | Command::Sunionstore(_)
                | Command::Zcard(_)
                | Command::Zcount(_)
                | Command::Zmscore(_)
                | Command::Zrange(_)
                | Command::Zrangebyscore(_)
                | Command::Zrangestore(_)
                | Command::Zrank(_)
                | Command::Zrem(_)
                | Command::Zremrangebyrank(_)
                | Command::Zremrangebyscore(_)
                | Command::Zrevrange(_)
                | Command::Zrevrank(_)
                | Command::Zscan(_)
                | Command::Zscore(_)
        )
    }
}
