impl Handler {
    fn can_apply_direct(command: &Command) -> bool {
        // GEOSEARCH and the GEORADIUS compatibility commands are read-only unless a
        // STORE/STOREDIST destination was parsed.  Keep the two-key variants in the
        // autocommit transaction, but do not wrap ordinary single-key geo reads.
        if matches!(
            command,
            Command::Geosearch(search)
                | Command::Georadius(search)
                | Command::Georadiusbymember(search)
                if search.stores_result()
        ) {
            return false;
        }
        if matches!(command, Command::Pfcount(pfcount) if !pfcount.is_single_key()) {
            return false;
        }
        if matches!(
            command,
            Command::Xread(read) if !read.is_single_stream()
        ) || matches!(
            command,
            Command::Xreadgroup(read) if !read.is_single_stream()
        ) {
            return false;
        }

        matches!(
            command,
            Command::Del(_)
                | Command::Unlink(_)
                | Command::Append(_)
                | Command::Bitcount(_)
                | Command::Bitfield(_)
                | Command::Bitop(_)
                | Command::Bitpos(_)
                | Command::Get(_)
                | Command::Getbit(_)
                | Command::GetDel(_)
                | Command::GetEx(_)
                | Command::GetRange(_)
                | Command::GetSet(_)
                | Command::Mget(_)
                | Command::Type(_)
                | Command::Ttl(_)
                | Command::Pttl(_)
                | Command::Expire(_)
                | Command::ExpireAt(_)
                | Command::ExpireTime(_)
                | Command::Pexpire(_)
                | Command::PexpireAt(_)
                | Command::PexpireTime(_)
                | Command::Persist(_)
                | Command::Exists(_)
                | Command::Touch(_)
                | Command::Dbsize(_)
                | Command::Keys(_)
                | Command::RandomKey(_)
                | Command::Scan(_)
                | Command::Scard(_)
                | Command::Sdiff(_)
                | Command::Sinter(_)
                | Command::Sismember(_)
                | Command::Smembers(_)
                | Command::Smismember(_)
                | Command::Srandmember(_)
                | Command::Sscan(_)
                | Command::Sunion(_)
                | Command::Zcard(_)
                | Command::Zcount(_)
                | Command::Zlexcount(_)
                | Command::Zmscore(_)
                | Command::Zrange(_)
                | Command::Zrangebylex(_)
                | Command::Zrangebyscore(_)
                | Command::Zrandmember(_)
                | Command::Zrank(_)
                | Command::Zrevrange(_)
                | Command::Zrevrangebylex(_)
                | Command::Zrevrangebyscore(_)
                | Command::Zrevrank(_)
                | Command::Zscan(_)
                | Command::Zscore(_)
                | Command::Strlen(_)
                | Command::Lindex(_)
                | Command::Linsert(_)
                | Command::Llen(_)
                | Command::Lpos(_)
                | Command::Lrange(_)
                | Command::Lpush(_)
                | Command::Lpushx(_)
                | Command::Lpop(_)
                | Command::Lrem(_)
                | Command::Lset(_)
                | Command::Ltrim(_)
                | Command::Rpop(_)
                | Command::Rpoplpush(_)
                | Command::Rpush(_)
                | Command::Rpushx(_)
                | Command::Set(_)
                | Command::Setbit(_)
                | Command::Setex(_)
                | Command::Setnx(_)
                | Command::SetRange(_)
                | Command::Psetex(_)
                | Command::Mset(_)
                | Command::Msetex(_)
                | Command::Msetnx(_)
                | Command::Incr(_)
                | Command::Incrby(_)
                | Command::IncrbyFloat(_)
                | Command::Decr(_)
                | Command::Decrby(_)
                | Command::Hset(_)
                | Command::Hsetnx(_)
                | Command::Hdel(_)
                | Command::Hexists(_)
                | Command::Hget(_)
                | Command::Hgetall(_)
                | Command::Hkeys(_)
                | Command::Hlen(_)
                | Command::Hmget(_)
                | Command::Hrandfield(_)
                | Command::Hscan(_)
                | Command::Hstrlen(_)
                | Command::Httl(_)
                | Command::Hpttl(_)
                | Command::HexpireTime(_)
                | Command::HpexpireTime(_)
                | Command::Hvals(_)
                | Command::Hincrby(_)
                | Command::HincrbyFloat(_)
                | Command::Hmset(_)
                | Command::Hgetdel(_)
                | Command::Hgetex(_)
                | Command::Hsetex(_)
                | Command::Hexpire(_)
                | Command::HexpireAt(_)
                | Command::Hpexpire(_)
                | Command::HpexpireAt(_)
                | Command::Hpersist(_)
                // These data types already implement their own key barriers and atomic
                // storage batches.  An outer auto-created transaction duplicates that
                // work and, for hot writes, can expose avoidable read-set conflicts.
                | Command::Geoadd(_)
                | Command::Geodist(_)
                | Command::Geohash(_)
                | Command::Geopos(_)
                | Command::Geosearch(_)
                | Command::Georadius(_)
                | Command::Georadiusbymember(_)
                | Command::Pfadd(_)
                | Command::Pfcount(_)
                | Command::Xadd(_)
                | Command::Xack(_)
                | Command::Xackdel(_)
                | Command::Xautoclaim(_)
                | Command::Xcfgset(_)
                | Command::Xclaim(_)
                | Command::Xdel(_)
                | Command::Xdelex(_)
                | Command::Xgroup(_)
                | Command::Xinfo(_)
                | Command::Xlen(_)
                | Command::Xpending(_)
                | Command::Xrange(_)
                | Command::Xread(_)
                | Command::Xreadgroup(_)
                | Command::Xrevrange(_)
                | Command::Xsetid(_)
                | Command::Xtrim(_)
                | Command::JsonSet(_)
                | Command::JsonGet(_)
                | Command::JsonDel(_)
                | Command::JsonType(_)
                | Command::JsonMGet(_)
                | Command::JsonNumIncrBy(_)
                | Command::JsonStrAppend(_)
                | Command::JsonArrAppend(_)
                | Command::JsonArrInsert(_)
                | Command::JsonArrPop(_)
                | Command::JsonObjKeys(_)
                | Command::VAdd(_)
                | Command::VSim(_)
                | Command::VRem(_)
                | Command::VCard(_)
                | Command::VDim(_)
                | Command::VEmb(_)
                | Command::VGetAttr(_)
                | Command::VSetAttr(_)
                | Command::VInfo(_)
                | Command::VRandMember(_)
                | Command::VLinks(_)
                | Command::VIsMember(_)
                | Command::VRange(_)
                | Command::FtCreate(_)
                | Command::FtList(_)
                | Command::FtDropIndex(_)
                | Command::FtAlter(_)
                | Command::FtAliasAdd(_)
                | Command::FtAliasUpdate(_)
                | Command::FtAliasDel(_)
                | Command::FtConfig(_)
                | Command::FtInfo(_)
                | Command::FtSearch(_)
                | Command::FtHybrid(_)
                | Command::FtAggregate(_)
                | Command::FtCursor(_)
                | Command::FtProfile(_)
                | Command::FtDict(_)
                | Command::FtSpellCheck(_)
                | Command::FtSug(_)
                | Command::FtSyn(_)
                | Command::FtUnsupported(_)
                | Command::Flushdb(_)
                | Command::Sadd(_)
                | Command::Spop(_)
                | Command::Srem(_)
                | Command::Zadd(_)
                | Command::Zincrby(_)
                | Command::Zrem(_)
                | Command::Zpopmax(_)
                | Command::Zpopmin(_)
                | Command::Zremrangebylex(_)
                | Command::Zremrangebyrank(_)
                | Command::Zremrangebyscore(_)
        )
    }

    fn can_apply_on_worker(command: &Command) -> bool {
        matches!(
            command,
            Command::Get(_)
                | Command::Mget(_)
                | Command::Type(_)
                | Command::Ttl(_)
                | Command::Pttl(_)
                | Command::ExpireTime(_)
                | Command::PexpireTime(_)
                | Command::Exists(_)
                | Command::Strlen(_)
                | Command::Dbsize(_)
                | Command::Flushdb(_)
                | Command::Keys(_)
                | Command::Scan(_)
                | Command::Lindex(_)
                | Command::Linsert(_)
                | Command::Llen(_)
                | Command::Lmpop(_)
                | Command::Lpos(_)
                | Command::Lrange(_)
                | Command::Copy(_)
                | Command::Move(_)
                | Command::Scard(_)
                | Command::Sdiff(_)
                | Command::Sdiffstore(_)
                | Command::Sinter(_)
                | Command::Sinterstore(_)
                | Command::Sismember(_)
                | Command::Smembers(_)
                | Command::Smismember(_)
                | Command::Spop(_)
                | Command::Srandmember(_)
                | Command::Sscan(_)
                | Command::Sunion(_)
                | Command::Sunionstore(_)
                | Command::Zcard(_)
                | Command::Zcount(_)
                | Command::Zlexcount(_)
                | Command::Zmscore(_)
                | Command::Zrange(_)
                | Command::Zrangebylex(_)
                | Command::Zrangebyscore(_)
                | Command::Zrandmember(_)
                | Command::Zrangestore(_)
                | Command::Zrank(_)
                | Command::Zrem(_)
                | Command::Zremrangebyrank(_)
                | Command::Zremrangebyscore(_)
                | Command::Zrevrange(_)
                | Command::Zrevrank(_)
                | Command::Zscan(_)
                | Command::Zscore(_)
        )
    }
}
