impl Handler {
    fn queue_transaction_frame(&mut self, frame: Frame, response_bytes: &mut Vec<u8>) {
        match Command::parse_from_frame(frame.clone()) {
            Ok(command) if Self::can_queue_transaction_command(&command) => {
                self.session.add_transaction_frame(frame);
                response_bytes.extend(Frame::SimpleString("QUEUED".to_string()).as_bytes());
            }
            Ok(command) => {
                self.session.mark_transaction_dirty();
                response_bytes.extend(
                    Frame::Error(format!(
                        "ERR command '{}' is not allowed in MULTI",
                        command.name()
                    ))
                    .as_bytes(),
                );
            }
            Err(error) => {
                self.session.mark_transaction_dirty();
                response_bytes.extend(Frame::Error(error.to_string()).as_bytes());
            }
        }
    }

    fn can_queue_transaction_command(command: &Command) -> bool {
        matches!(
            command,
            Command::Append(_)
                | Command::Copy(_)
                | Command::Dbsize(_)
                | Command::Decr(_)
                | Command::Decrby(_)
                | Command::Del(_)
                | Command::Exists(_)
                | Command::Expire(_)
                | Command::ExpireAt(_)
                | Command::ExpireTime(_)
                | Command::Flushdb(_)
                | Command::Get(_)
                | Command::GetDel(_)
                | Command::GetEx(_)
                | Command::GetRange(_)
                | Command::GetSet(_)
                | Command::Hdel(_)
                | Command::Hexists(_)
                | Command::Hget(_)
                | Command::Hgetall(_)
                | Command::Hincrby(_)
                | Command::HincrbyFloat(_)
                | Command::Hkeys(_)
                | Command::Hlen(_)
                | Command::Hmget(_)
                | Command::Hmset(_)
                | Command::Hscan(_)
                | Command::Hrandfield(_)
                | Command::Hset(_)
                | Command::Hsetnx(_)
                | Command::Hstrlen(_)
                | Command::Hvals(_)
                | Command::Incr(_)
                | Command::Incrby(_)
                | Command::IncrbyFloat(_)
                | Command::Keys(_)
                | Command::Lindex(_)
                | Command::Linsert(_)
                | Command::Llen(_)
                | Command::Lmove(_)
                | Command::Lmpop(_)
                | Command::Lpop(_)
                | Command::Lpos(_)
                | Command::Lpush(_)
                | Command::Lpushx(_)
                | Command::Lrange(_)
                | Command::Lset(_)
                | Command::Ltrim(_)
                | Command::Move(_)
                | Command::Mget(_)
                | Command::Mset(_)
                | Command::Msetnx(_)
                | Command::Persist(_)
                | Command::Pexpire(_)
                | Command::PexpireAt(_)
                | Command::PexpireTime(_)
                | Command::Psetex(_)
                | Command::Pttl(_)
                | Command::RandomKey(_)
                | Command::Rename(_)
                | Command::Renamenx(_)
                | Command::Rpop(_)
                | Command::Rpoplpush(_)
                | Command::Rpush(_)
                | Command::Rpushx(_)
                | Command::Sadd(_)
                | Command::Scard(_)
                | Command::Scan(_)
                | Command::Sdiff(_)
                | Command::Sdiffstore(_)
                | Command::Set(_)
                | Command::SetRange(_)
                | Command::Setex(_)
                | Command::Setnx(_)
                | Command::Sinter(_)
                | Command::Sismember(_)
                | Command::Sinterstore(_)
                | Command::Smismember(_)
                | Command::Smembers(_)
                | Command::Spop(_)
                | Command::Srandmember(_)
                | Command::Srem(_)
                | Command::Sscan(_)
                | Command::Strlen(_)
                | Command::Sunion(_)
                | Command::Sunionstore(_)
                | Command::Ttl(_)
                | Command::Touch(_)
                | Command::Type(_)
                | Command::Unlink(_)
                | Command::Xack(_)
                | Command::Xadd(_)
                | Command::Xautoclaim(_)
                | Command::Xclaim(_)
                | Command::Xdel(_)
                | Command::Xgroup(_)
                | Command::Xinfo(_)
                | Command::Xlen(_)
                | Command::Xpending(_)
                | Command::Xrange(_)
                | Command::Xread(_)
                | Command::Xreadgroup(_)
                | Command::Xrevrange(_)
                | Command::Xtrim(_)
                | Command::Zadd(_)
                | Command::Zcard(_)
                | Command::Zcount(_)
                | Command::Zincrby(_)
                | Command::Zmscore(_)
                | Command::Zrange(_)
                | Command::Zrangebyscore(_)
                | Command::Zrangestore(_)
                | Command::Zrank(_)
                | Command::Zrem(_)
                | Command::Zremrangebyrank(_)
                | Command::Zremrangebyscore(_)
                | Command::Zrevrange(_)
                | Command::Zrevrank(_)
                | Command::Zscan(_)
                | Command::Zscore(_)
        )
    }
}
