use super::*;

impl Command {
    pub fn propagate_aof_if_needed(&self) -> bool {
        match self {
            Command::Bitfield(bitfield) => return !bitfield.is_read_only(),
            Command::Georadius(georadius) | Command::Georadiusbymember(georadius) => {
                return georadius.stores_result();
            }
            Command::FtConfig(config) => return config.may_write_data(),
            Command::FtDict(dict) => return dict.may_write_data(),
            Command::FtSug(suggestion) => return suggestion.may_write_data(),
            Command::FtSyn(synonym) => return synonym.may_write_data(),
            Command::Lua(lua) => return lua.may_write_data(),
            Command::Wasm(wasm) => return wasm.may_write_data(),
            _ => {}
        }

        matches!(
            self,
            Command::Del(_)
                | Command::Copy(_)
                | Command::Bitop(_)
                | Command::Setbit(_)
                | Command::GetDel(_)
                | Command::GetEx(_)
                | Command::Geoadd(_)
                | Command::Geosearchstore(_)
                | Command::Expire(_)
                | Command::ExpireAt(_)
                | Command::Persist(_)
                | Command::Pexpire(_)
                | Command::PexpireAt(_)
                | Command::Pfadd(_)
                | Command::Pfmerge(_)
                | Command::Rename(_)
                | Command::Renamenx(_)
                | Command::Append(_)
                | Command::Decr(_)
                | Command::Decrby(_)
                | Command::GetSet(_)
                | Command::Incr(_)
                | Command::Incrby(_)
                | Command::IncrbyFloat(_)
                | Command::Mset(_)
                | Command::Msetex(_)
                | Command::Msetnx(_)
                | Command::Set(_)
                | Command::Setex(_)
                | Command::Setnx(_)
                | Command::SetRange(_)
                | Command::Flushall(_)
                | Command::FtCreate(_)
                | Command::FtDropIndex(_)
                | Command::FtAlter(_)
                | Command::FtAliasAdd(_)
                | Command::FtAliasUpdate(_)
                | Command::FtAliasDel(_)
                | Command::Flushdb(_)
                | Command::Blmove(_)
                | Command::Blmpop(_)
                | Command::Blpop(_)
                | Command::Brpop(_)
                | Command::Brpoplpush(_)
                | Command::Hdel(_)
                | Command::Hexpire(_)
                | Command::HexpireAt(_)
                | Command::Hgetdel(_)
                | Command::Hgetex(_)
                | Command::Hincrby(_)
                | Command::HincrbyFloat(_)
                | Command::Hmset(_)
                | Command::Hpersist(_)
                | Command::Hpexpire(_)
                | Command::HpexpireAt(_)
                | Command::Hset(_)
                | Command::Hsetex(_)
                | Command::Hsetnx(_)
                | Command::Linsert(_)
                | Command::Lmove(_)
                | Command::Lmpop(_)
                | Command::Lpop(_)
                | Command::Lpush(_)
                | Command::Lpushx(_)
                | Command::Lrem(_)
                | Command::Lset(_)
                | Command::Ltrim(_)
                | Command::Rpop(_)
                | Command::Rpoplpush(_)
                | Command::Rpush(_)
                | Command::Rpushx(_)
                | Command::Sadd(_)
                | Command::Sdiffstore(_)
                | Command::Sinterstore(_)
                | Command::Smove(_)
                | Command::Spop(_)
                | Command::Srem(_)
                | Command::Sunionstore(_)
                | Command::Unlink(_)
                | Command::Bzmpop(_)
                | Command::Bzpopmax(_)
                | Command::Bzpopmin(_)
                | Command::Zadd(_)
                | Command::Zdiffstore(_)
                | Command::Zincrby(_)
                | Command::Zinterstore(_)
                | Command::Zmpop(_)
                | Command::Zpopmax(_)
                | Command::Zpopmin(_)
                | Command::Zrangestore(_)
                | Command::Zrem(_)
                | Command::Zremrangebylex(_)
                | Command::Zremrangebyrank(_)
                | Command::Zremrangebyscore(_)
                | Command::Zunionstore(_)
                | Command::Xack(_)
                | Command::Xackdel(_)
                | Command::Xadd(_)
                | Command::Xautoclaim(_)
                | Command::Xclaim(_)
                | Command::Xdel(_)
                | Command::Xdelex(_)
                | Command::Xgroup(_)
                | Command::Xreadgroup(_)
                | Command::Xsetid(_)
                | Command::Xtrim(_)
                | Command::JsonSet(_)
                | Command::JsonDel(_)
                | Command::VAdd(_)
                | Command::VRem(_)
                | Command::VSetAttr(_)
                | Command::Psetex(_)
                | Command::Move(_)
        )
    }
}
