use super::*;

pub fn handle_command_async(
    db: &Db,
    command: Command,
) -> std::pin::Pin<Box<dyn std::future::Future<Output = Result<Frame, Error>> + Send + '_>> {
    Box::pin(async move {
        match command {
            Command::Bitcount(bitcount) => bitcount.apply_async(db).await,
            Command::Set(set) => set.apply_async(db).await,
            Command::Bitfield(bitfield) => bitfield.apply_async(db).await,
            Command::Bitop(bitop) => bitop.apply_async(db).await,
            Command::Bitpos(bitpos) => bitpos.apply_async(db).await,
            Command::Get(get) => get.apply_async(db).await,
            Command::Getbit(getbit) => getbit.apply_async(db).await,
            Command::GetRange(getrange) => getrange.apply_async(db).await,
            Command::Lcs(lcs) => lcs.apply_async(db).await,
            Command::Setex(setex) => setex.apply_async(db).await,
            Command::Setnx(setnx) => setnx.apply_async(db).await,
            Command::Psetex(psetex) => psetex.apply_async(db).await,
            Command::Mset(mset) => mset.apply_async(db).await,
            Command::Mget(mget) => mget.apply_async(db).await,
            Command::Msetnx(msetnx) => msetnx.apply_async(db).await,
            Command::Incr(incr) => incr.apply_async(db).await,
            Command::Incrby(incrby) => incrby.apply_async(db).await,
            Command::Decr(decr) => decr.apply_async(db).await,
            Command::Decrby(decrby) => decrby.apply_async(db).await,
            Command::Append(append) => append.apply_async(db).await,
            Command::SetRange(setrange) => setrange.apply_async(db).await,
            Command::Setbit(setbit) => setbit.apply_async(db).await,
            Command::GetSet(getset) => getset.apply_async(db).await,
            Command::GetDel(getdel) => getdel.apply_async(db).await,
            Command::GetEx(getex) => getex.apply_async(db).await,
            Command::Msetex(msetex) => msetex.apply_async(db).await,
            Command::Strlen(strlen) => strlen.apply_async(db).await,
            Command::IncrbyFloat(incrbyfloat) => incrbyfloat.apply_async(db).await,
            Command::Hset(hset) => hset.apply_async(db).await,
            Command::Hdel(hdel) => hdel.apply_async(db).await,
            Command::Hexists(hexists) => hexists.apply_async(db).await,
            Command::Hget(hget) => hget.apply_async(db).await,
            Command::Hgetall(hgetall) => hgetall.apply_async(db).await,
            Command::Hkeys(hkeys) => hkeys.apply_async(db).await,
            Command::Hlen(hlen) => hlen.apply_async(db).await,
            Command::Hmget(hmget) => hmget.apply_async(db).await,
            Command::Hrandfield(hrandfield) => hrandfield.apply_async(db).await,
            Command::Hscan(hscan) => hscan.apply_async(db).await,
            Command::Hstrlen(hstrlen) => hstrlen.apply_async(db).await,
            Command::Httl(httl) => httl.apply_async(db).await,
            Command::Hpttl(hpttl) => hpttl.apply_async(db).await,
            Command::HexpireTime(hexpiretime) => hexpiretime.apply_async(db).await,
            Command::HpexpireTime(hpexpiretime) => hpexpiretime.apply_async(db).await,
            Command::Hvals(hvals) => hvals.apply_async(db).await,
            Command::Hmset(hmset) => hmset.apply_async(db).await,
            Command::Hsetnx(hsetnx) => hsetnx.apply_async(db).await,
            Command::Hincrby(hincrby) => hincrby.apply_async(db).await,
            Command::HincrbyFloat(hincrbyfloat) => hincrbyfloat.apply_async(db).await,
            Command::Hgetdel(hgetdel) => hgetdel.apply_async(db).await,
            Command::Hgetex(hgetex) => hgetex.apply_async(db).await,
            Command::Hsetex(hsetex) => hsetex.apply_async(db).await,
            Command::Hexpire(hexpire) => hexpire.apply_async(db).await,
            Command::HexpireAt(hexpireat) => hexpireat.apply_async(db).await,
            Command::Hpexpire(hpexpire) => hpexpire.apply_async(db).await,
            Command::HpexpireAt(hpexpireat) => hpexpireat.apply_async(db).await,
            Command::Hpersist(hpersist) => hpersist.apply_async(db).await,
            Command::Del(del) => del.apply_async(db).await,
            Command::Unlink(unlink) => unlink.apply_async(db).await,
            Command::Expire(expire) => expire.apply_async(db).await,
            Command::ExpireAt(expireat) => expireat.apply_async(db).await,
            Command::Pexpire(pexpire) => pexpire.apply_async(db).await,
            Command::PexpireAt(pexpireat) => pexpireat.apply_async(db).await,
            Command::Persist(persist) => persist.apply_async(db).await,
            Command::Rename(rename) => rename.apply_async(db).await,
            Command::Renamenx(renamenx) => renamenx.apply_async(db).await,
            Command::Flushdb(flushdb) => flushdb.apply_async(db).await,
            Command::Exists(exists) => exists.apply_async(db).await,
            Command::ExpireTime(expiretime) => expiretime.apply_async(db).await,
            Command::PexpireTime(pexpiretime) => pexpiretime.apply_async(db).await,
            Command::RandomKey(randomkey) => randomkey.apply_async(db).await,
            Command::Touch(touch) => touch.apply_async(db).await,
            Command::Ttl(ttl) => ttl.apply_async(db).await,
            Command::Pttl(pttl) => pttl.apply_async(db).await,
            Command::Type(r#type) => r#type.apply_async(db).await,
            Command::Lrange(lrange) => lrange.apply_async(db).await,
            Command::Dbsize(dbsize) => dbsize.apply_async(db).await,
            Command::Keys(keys) => keys.apply_async(db).await,
            Command::Scan(scan) => scan.apply_async(db).await,
            Command::Sdiff(sdiff) => sdiff.apply_async(db).await,
            Command::Sdiffstore(sdiffstore) => sdiffstore.apply_async(db).await,
            Command::Sadd(sadd) => sadd.apply_async(db).await,
            Command::Scard(scard) => scard.apply_async(db).await,
            Command::Sismember(sismember) => sismember.apply_async(db).await,
            Command::Sintercard(sintercard) => sintercard.apply_async(db).await,
            Command::Smismember(smismember) => smismember.apply_async(db).await,
            Command::Srem(srem) => srem.apply_async(db).await,
            Command::Sinter(sinter) => sinter.apply_async(db).await,
            Command::Sinterstore(sinterstore) => sinterstore.apply_async(db).await,
            Command::Smembers(smembers) => smembers.apply_async(db).await,
            Command::Spop(spop) => spop.apply_async(db).await,
            Command::Srandmember(srandmember) => srandmember.apply_async(db).await,
            Command::Sscan(sscan) => sscan.apply_async(db).await,
            Command::Sunion(sunion) => sunion.apply_async(db).await,
            Command::Sunionstore(sunionstore) => sunionstore.apply_async(db).await,
            Command::Zcard(zcard) => zcard.apply_async(db).await,
            Command::Zadd(zadd) => zadd.apply_async(db).await,
            Command::Zincrby(zincrby) => zincrby.apply_async(db).await,
            Command::Zcount(zcount) => zcount.apply_async(db).await,
            Command::Zdiff(zdiff) => zdiff.apply_async(db).await,
            Command::Zrange(zrange) => zrange.apply_async(db).await,
            Command::Zrangebylex(zrangebylex) => zrangebylex.apply_async(db).await,
            Command::Zrank(zrank) => zrank.apply_async(db).await,
            Command::Zrem(zrem) => zrem.apply_async(db).await,
            Command::Zremrangebyrank(zremrangebyrank) => zremrangebyrank.apply_async(db).await,
            Command::Zremrangebyscore(zremrangebyscore) => zremrangebyscore.apply_async(db).await,
            Command::Zdiffstore(zdiffstore) => zdiffstore.apply_async(db).await,
            Command::Zinter(zinter) => zinter.apply_async(db).await,
            Command::Zintercard(zintercard) => zintercard.apply_async(db).await,
            Command::Zinterstore(zinterstore) => zinterstore.apply_async(db).await,
            Command::Zlexcount(zlexcount) => zlexcount.apply_async(db).await,
            Command::Zmscore(zmscore) => zmscore.apply_async(db).await,
            Command::Zrandmember(zrandmember) => zrandmember.apply_async(db).await,
            Command::Zunionstore(zunionstore) => zunionstore.apply_async(db).await,
            Command::Zpopmax(zpopmax) => zpopmax.apply_async(db).await,
            Command::Zpopmin(zpopmin) => zpopmin.apply_async(db).await,
            Command::Zremrangebylex(zremrangebylex) => zremrangebylex.apply_async(db).await,
            Command::Zrevrange(zrevrange) => zrevrange.apply_async(db).await,
            Command::Zrevrangebylex(zrevrangebylex) => zrevrangebylex.apply_async(db).await,
            Command::Zrevrangebyscore(zrevrangebyscore) => zrevrangebyscore.apply_async(db).await,
            Command::Zrevrank(zrevrank) => zrevrank.apply_async(db).await,
            Command::Zrangebyscore(zrangebyscore) => zrangebyscore.apply_async(db).await,
            Command::Zrangestore(zrangestore) => zrangestore.apply_async(db).await,
            Command::Zscan(zscan) => zscan.apply_async(db).await,
            Command::Zscore(zscore) => zscore.apply_async(db).await,
            Command::Zunion(zunion) => zunion.apply_async(db).await,
            Command::Lindex(lindex) => lindex.apply_async(db).await,
            Command::Llen(llen) => llen.apply_async(db).await,
            Command::Lpos(lpos) => lpos.apply_async(db).await,
            Command::Lpush(lpush) => lpush.apply_async(db).await,
            Command::Lpushx(lpushx) => lpushx.apply_async(db).await,
            Command::Rpush(rpush) => rpush.apply_async(db).await,
            Command::Rpushx(rpushx) => rpushx.apply_async(db).await,
            Command::Lpop(lpop) => lpop.apply_async(db).await,
            Command::Rpop(rpop) => rpop.apply_async(db).await,
            Command::Lset(lset) => lset.apply_async(db).await,
            Command::Ltrim(ltrim) => ltrim.apply_async(db).await,
            Command::Linsert(linsert) => linsert.apply_async(db).await,
            Command::Lrem(lrem) => lrem.apply_async(db).await,
            Command::Lmpop(lmpop) => lmpop.apply_async(db).await,
            Command::Blpop(blpop) => blpop.apply_async(db).await,
            Command::Brpop(brpop) => brpop.apply_async(db).await,
            Command::Brpoplpush(brpoplpush) => brpoplpush.apply_async(db).await,
            Command::Blmove(blmove) => blmove.apply_async(db).await,
            Command::Blmpop(blmpop) => blmpop.apply_async(db).await,
            Command::Rpoplpush(rpoplpush) => rpoplpush.apply_async(db).await,
            Command::Lmove(lmove) => lmove.apply_async(db).await,
            Command::Smove(smove) => smove.apply_async(db).await,
            Command::Geoadd(geoadd) => geoadd.apply_async(db).await,
            Command::Geodist(geodist) => geodist.apply_async(db).await,
            Command::Geohash(geohash) => geohash.apply_async(db).await,
            Command::Geopos(geopos) => geopos.apply_async(db).await,
            Command::Geosearch(geosearch) => geosearch.apply_async(db).await,
            Command::Georadius(georadius) => georadius.apply_async(db).await,
            Command::Georadiusbymember(georadiusbymember) => {
                georadiusbymember.apply_async(db).await
            }
            Command::Geosearchstore(geosearchstore) => geosearchstore.apply_async(db).await,
            Command::Pfadd(pfadd) => pfadd.apply_async(db).await,
            Command::Pfcount(pfcount) => pfcount.apply_async(db).await,
            Command::Pfmerge(pfmerge) => pfmerge.apply_async(db).await,
            Command::Xadd(xadd) => xadd.apply_async(db).await,
            Command::Xdel(xdel) => xdel.apply_async(db).await,
            Command::Xtrim(xtrim) => xtrim.apply_async(db).await,
            Command::Xack(xack) => xack.apply_async(db).await,
            Command::Xackdel(xackdel) => xackdel.apply_async(db).await,
            Command::Xautoclaim(xautoclaim) => xautoclaim.apply_async(db).await,
            Command::Xcfgset(xcfgset) => xcfgset.apply_async(db).await,
            Command::Xclaim(xclaim) => xclaim.apply_async(db).await,
            Command::Xdelex(xdelex) => xdelex.apply_async(db).await,
            Command::Xgroup(xgroup) => xgroup.apply_async(db).await,
            Command::Xinfo(xinfo) => xinfo.apply_async(db).await,
            Command::Xlen(xlen) => xlen.apply_async(db).await,
            Command::Xpending(xpending) => xpending.apply_async(db).await,
            Command::Xrange(xrange) => xrange.apply_async(db).await,
            Command::Xread(xread) => xread.apply_async(db).await,
            Command::Xsetid(xsetid) => xsetid.apply_async(db).await,
            Command::Xrevrange(xrevrange) => xrevrange.apply_async(db).await,
            Command::Xreadgroup(xreadgroup) => xreadgroup.apply_async(db).await,
            Command::Zmpop(zmpop) => zmpop.apply_async(db).await,
            Command::Bzpopmin(bzpopmin) => bzpopmin.apply_async(db).await,
            Command::Bzpopmax(bzpopmax) => bzpopmax.apply_async(db).await,
            Command::Bzmpop(bzmpop) => bzmpop.apply_async(db).await,
            Command::JsonSet(json_set) => json_set.apply_async(db).await,
            Command::JsonGet(json_get) => json_get.apply_async(db).await,
            Command::JsonDel(json_del) => json_del.apply_async(db).await,
            Command::JsonType(json_type) => json_type.apply_async(db).await,
            Command::FtCreate(ft_create) => ft_create.apply_async(db).await,
            Command::FtList(ft_list) => ft_list.apply_async(db).await,
            Command::FtDropIndex(ft_drop_index) => ft_drop_index.apply_async(db).await,
            Command::FtAlter(ft_alter) => ft_alter.apply_async(db).await,
            Command::FtAliasAdd(ft_alias_add) => ft_alias_add.apply_async(db).await,
            Command::FtAliasUpdate(ft_alias_update) => ft_alias_update.apply_async(db).await,
            Command::FtAliasDel(ft_alias_del) => ft_alias_del.apply_async(db).await,
            Command::FtConfig(ft_config) => ft_config.apply_async(db).await,
            Command::FtInfo(ft_info) => ft_info.apply_async(db).await,
            Command::FtSearch(ft_search) => ft_search.apply_async(db).await,
            Command::FtHybrid(ft_hybrid) => ft_hybrid.apply_async(db).await,
            Command::FtAggregate(ft_aggregate) => ft_aggregate.apply_async(db).await,
            Command::FtCursor(ft_cursor) => ft_cursor.apply_async(db).await,
            Command::FtProfile(ft_profile) => ft_profile.apply_async(db).await,
            Command::FtExplain(ft_explain) => ft_explain.apply_async(db).await,
            Command::FtTagVals(ft_tagvals) => ft_tagvals.apply_async(db).await,
            Command::FtDict(ft_dict) => ft_dict.apply_async(db).await,
            Command::FtSpellCheck(ft_spellcheck) => ft_spellcheck.apply_async(db).await,
            Command::FtSug(ft_sug) => ft_sug.apply_async(db).await,
            Command::FtSyn(ft_syn) => ft_syn.apply_async(db).await,
            Command::FtUnsupported(ft_unsupported) => ft_unsupported.apply_async().await,
            Command::Lua(lua) => lua.apply_async(db).await,
            Command::VAdd(vadd) => vadd.apply_async(db).await,
            Command::VSim(vsim) => vsim.apply_async(db).await,
            Command::VRem(vrem) => vrem.apply_async(db).await,
            Command::VCard(vcard) => vcard.apply_async(db).await,
            Command::VDim(vdim) => vdim.apply_async(db).await,
            Command::VEmb(vemb) => vemb.apply_async(db).await,
            Command::VGetAttr(vgetattr) => vgetattr.apply_async(db).await,
            Command::VSetAttr(vsetattr) => vsetattr.apply_async(db).await,
            Command::VInfo(vinfo) => vinfo.apply_async(db).await,
            Command::VRandMember(vrandmember) => vrandmember.apply_async(db).await,
            Command::VLinks(vlinks) => vlinks.apply_async(db).await,
            Command::Copy(copy) => {
                let copied = db
                    .copy_key_to_db_async(
                        copy.db_index().unwrap_or(db.db_index() as usize) as u16,
                        copy.source(),
                        copy.destination(),
                        copy.replace(),
                    )
                    .await?;
                Ok(Frame::Integer(if copied { 1 } else { 0 }))
            }
            Command::Move(r#move) => {
                let moved = db
                    .move_key_to_db_async(r#move.get_db_index() as u16, r#move.get_key())
                    .await?;
                Ok(Frame::Integer(if moved { 1 } else { 0 }))
            }
            Command::Flushall(_) => {
                db.clear_async().await;
                Ok(Frame::Ok)
            }
            Command::Info(info) => info.apply_async(db).await,
            Command::Save(_) => Ok(Frame::Ok),
            Command::Bgsave(_) => Ok(Frame::Ok),
            other => handle_command(db, other),
        }
    })
}
