use anyhow::Error;

use crate::{
    cmds::{
        bitmap::{
            bitcount::Bitcount, bitfield::Bitfield, bitop::Bitop, bitpos::Bitpos, getbit::Getbit,
            setbit::Setbit,
        },
        connect::{auth::Auth, client::Client, echo::Echo, ping::Ping, select::Select},
        full_text::{
            FtAggregate, FtAliasAdd, FtAliasDel, FtAliasUpdate, FtAlter, FtConfig, FtCreate,
            FtCursor, FtDict, FtDropIndex, FtExplain, FtHybrid, FtInfo, FtList, FtProfile,
            FtSearch, FtSpellCheck, FtSug, FtSyn, FtTagVals, FtUnsupported,
        },
        geo::{
            Geoadd, Geodist, Geohash, Geopos, Georadius, Georadiusbymember, Geosearch,
            Geosearchstore,
        },
        hash::{
            hdel::Hdel, hexists::Hexists, hexpire::Hexpire, hget::Hget, hgetall::Hgetall,
            hgetdel::Hgetdel, hgetex::Hgetex, hincrby::Hincrby, hincrbyfloat::HincrbyFloat,
            hkeys::Hkeys, hlen::Hlen, hmget::Hmget, hmset::Hmset, hpersist::Hpersist,
            hrandfield::Hrandfield, hscan::Hscan, hset::Hset, hsetex::Hsetex, hsetnx::Hsetnx,
            hstrlen::Hstrlen, httl::Httl, hvals::Hvals,
        },
        hll::{pfadd::Pfadd, pfcount::Pfcount, pfmerge::Pfmerge},
        json::{JsonDel, JsonGet, JsonSet, JsonType},
        key::{
            copy::Copy, del::Del, exists::Exists, expire::Expire, expireat::ExpireAt,
            expiretime::ExpireTime, keys::Keys, r#move::Move, persist::Persist, pexpire::Pexpire,
            pexpireat::PexpireAt, pexpiretime::PexpireTime, pttl::Pttl, randomkey::RandomKey,
            rename::Rename, renamenx::Renamenx, scan::Scan, touch::Touch, ttl::Ttl, r#type::Type,
            unlink::Unlink,
        },
        listing::{
            blmove::Blmove, blmpop::Blmpop, blpop::Blpop, brpop::Brpop, brpoplpush::Brpoplpush,
            lindex::Lindex, linsert::Linsert, llen::Llen, lmove::Lmove, lmpop::Lmpop, lpop::Lpop,
            lpos::Lpos, lpush::Lpush, lpushx::Lpushx, lrange::Lrange, lrem::Lrem, lset::Lset,
            ltrim::Ltrim, rpop::Rpop, rpoplpush::Rpoplpush, rpush::Rpush, rpushx::Rpushx,
        },
        lua::LuaCommand,
        server::{
            bgsave::Bgsave, config::Config, dbsize::Dbsize, flushall::Flushall, flushdb::Flushdb,
            info::Info, save::Save,
        },
        set::{
            sadd::Sadd, scard::Scard, sdiff::Sdiff, sdiffstore::Sdiffstore, sinter::Sinter,
            sintercard::Sintercard, sinterstore::Sinterstore, sismember::Sismember,
            smembers::Smembers, smismember::Smismember, smove::Smove, spop::Spop,
            srandmember::Srandmember, srem::Srem, sscan::Sscan, sunion::Sunion,
            sunionstore::Sunionstore,
        },
        sorted_set::{
            bzmpop::Bzmpop, bzpopmax::Bzpopmax, bzpopmin::Bzpopmin, zadd::Zadd, zcard::Zcard,
            zcount::Zcount, zdiff::Zdiff, zdiffstore::Zdiffstore, zincrby::Zincrby, zinter::Zinter,
            zintercard::Zintercard, zinterstore::Zinterstore, zlexcount::Zlexcount, zmpop::Zmpop,
            zmscore::Zmscore, zpopmax::Zpopmax, zpopmin::Zpopmin, zrandmember::Zrandmember,
            zrange::Zrange, zrangebylex::Zrangebylex, zrangebyscore::Zrangebyscore,
            zrangestore::Zrangestore, zrank::Zrank, zrem::Zrem, zremrangebylex::Zremrangebylex,
            zremrangebyrank::Zremrangebyrank, zremrangebyscore::Zremrangebyscore,
            zrevrange::Zrevrange, zrevrangebylex::Zrevrangebylex,
            zrevrangebyscore::Zrevrangebyscore, zrevrank::Zrevrank, zscan::Zscan, zscore::Zscore,
            zunion::Zunion, zunionstore::Zunionstore,
        },
        stream::{
            xack::Xack, xackdel::Xackdel, xadd::Xadd, xautoclaim::Xautoclaim, xcfgset::Xcfgset,
            xclaim::Xclaim, xdel::Xdel, xdelex::Xdelex, xgroup::Xgroup, xinfo::Xinfo, xlen::Xlen,
            xpending::Xpending, xrange::Xrange, xread::Xread, xreadgroup::Xreadgroup,
            xrevrange::Xrevrange, xsetid::Xsetid, xtrim::Xtrim,
        },
        string::{
            append::Append, decr::Decr, decrby::Decrby, get::Get, getdel::GetDel, getex::GetEx,
            getrange::GetRange, getset::GetSet, incr::Incr, incrby::Incrby,
            incrbyfloat::IncrbyFloat, lcs::Lcs, mget::Mget, mset::Mset, msetex::Msetex,
            msetnx::Msetnx, psetex::Psetex, set::Set, setex::Setex, setnx::Setnx,
            setrange::SetRange, strlen::Strlen,
        },
        transaction::{discard::Discard, exec::Exec, multi::Multi, unwatch::Unwatch, watch::Watch},
        unknown::Unknown,
        vector::{
            VAdd, VCard, VDim, VEmb, VGetAttr, VInfo, VLinks, VRandMember, VRem, VSetAttr, VSim,
        },
        wasm::WasmCommand,
    },
    frame::Frame,
};
// 命令
pub enum Command {
    Auth(Auth),
    Append(Append),
    Bitcount(Bitcount),
    Bitfield(Bitfield),
    Bitop(Bitop),
    Bitpos(Bitpos),
    Client(Client),
    Config(Config),
    Copy(Copy),
    Dbsize(Dbsize),
    Expire(Expire),
    ExpireTime(ExpireTime),
    Del(Del),
    Keys(Keys),
    Flushdb(Flushdb),
    FtCreate(FtCreate),
    FtList(FtList),
    FtDropIndex(FtDropIndex),
    FtAlter(FtAlter),
    FtAliasAdd(FtAliasAdd),
    FtAliasUpdate(FtAliasUpdate),
    FtAliasDel(FtAliasDel),
    FtConfig(FtConfig),
    FtInfo(FtInfo),
    FtSearch(FtSearch),
    FtHybrid(FtHybrid),
    FtAggregate(FtAggregate),
    FtCursor(FtCursor),
    FtProfile(FtProfile),
    FtExplain(FtExplain),
    FtTagVals(FtTagVals),
    FtDict(FtDict),
    FtSpellCheck(FtSpellCheck),
    FtSug(FtSug),
    FtSyn(FtSyn),
    FtUnsupported(FtUnsupported),
    Get(Get),
    Geoadd(Geoadd),
    Geodist(Geodist),
    Geohash(Geohash),
    Geopos(Geopos),
    Georadius(Georadius),
    Georadiusbymember(Georadiusbymember),
    Geosearch(Geosearch),
    Geosearchstore(Geosearchstore),
    Getbit(Getbit),
    GetDel(GetDel),
    GetEx(GetEx),
    GetRange(GetRange),
    Lcs(Lcs),
    Ping(Ping),
    Pfadd(Pfadd),
    Pfcount(Pfcount),
    Pfmerge(Pfmerge),
    Pttl(Pttl),
    Scan(Scan),
    Select(Select),
    Set(Set),
    Setbit(Setbit),
    Setex(Setex),
    Setnx(Setnx),
    SetRange(SetRange),
    Ttl(Ttl),
    Unknown(Unknown),
    Mset(Mset),
    Msetex(Msetex),
    Msetnx(Msetnx),
    Mget(Mget),
    Strlen(Strlen),
    Sunionstore(Sunionstore),
    Renamenx(Renamenx),
    Rename(Rename),
    Exists(Exists),
    Hset(Hset),
    Hexpire(Hexpire),
    HexpireAt(Hexpire),
    HexpireTime(Httl),
    Hgetdel(Hgetdel),
    Hgetex(Hgetex),
    Hpersist(Hpersist),
    Hpexpire(Hexpire),
    HpexpireAt(Hexpire),
    HpexpireTime(Httl),
    Hpttl(Httl),
    Hincrby(Hincrby),
    HincrbyFloat(HincrbyFloat),
    Hget(Hget),
    Type(Type),
    Hmset(Hmset),
    Hexists(Hexists),
    Hstrlen(Hstrlen),
    Hmget(Hmget),
    Hdel(Hdel),
    Hlen(Hlen),
    Hscan(Hscan),
    Hrandfield(Hrandfield),
    Hsetnx(Hsetnx),
    Hsetex(Hsetex),
    Hgetall(Hgetall),
    Httl(Httl),
    Hkeys(Hkeys),
    Blmove(Blmove),
    Blmpop(Blmpop),
    Blpop(Blpop),
    Brpop(Brpop),
    Brpoplpush(Brpoplpush),
    Lindex(Lindex),
    Linsert(Linsert),
    Persist(Persist),
    Lmove(Lmove),
    Rpop(Rpop),
    Rpoplpush(Rpoplpush),
    Lpop(Lpop),
    Lpos(Lpos),
    Llen(Llen),
    Lrem(Lrem),
    Hvals(Hvals),
    Rpush(Rpush),
    Lmpop(Lmpop),
    Lpush(Lpush),
    Sadd(Sadd),
    Sismember(Sismember),
    Smembers(Smembers),
    Scard(Scard),
    Sdiff(Sdiff),
    Sdiffstore(Sdiffstore),
    Sinter(Sinter),
    Sintercard(Sintercard),
    Sinterstore(Sinterstore),
    Smove(Smove),
    Spop(Spop),
    Srem(Srem),
    Flushall(Flushall),
    Lpushx(Lpushx),
    Rpushx(Rpushx),
    Decr(Decr),
    Incr(Incr),
    IncrbyFloat(IncrbyFloat),
    Lset(Lset),
    Ltrim(Ltrim),
    Sunion(Sunion),
    Bzmpop(Bzmpop),
    Bzpopmax(Bzpopmax),
    Bzpopmin(Bzpopmin),
    Zcount(Zcount),
    Zadd(Zadd),
    Zdiff(Zdiff),
    Zdiffstore(Zdiffstore),
    Zincrby(Zincrby),
    Zinter(Zinter),
    Zintercard(Zintercard),
    Zinterstore(Zinterstore),
    Zlexcount(Zlexcount),
    Zmpop(Zmpop),
    Zscore(Zscore),
    Zcard(Zcard),
    Zpopmax(Zpopmax),
    Zpopmin(Zpopmin),
    Zrandmember(Zrandmember),
    Zrank(Zrank),
    Zrem(Zrem),
    Zremrangebylex(Zremrangebylex),
    Zremrangebyrank(Zremrangebyrank),
    Zremrangebyscore(Zremrangebyscore),
    Zrange(Zrange),
    Zrangebylex(Zrangebylex),
    Zrangestore(Zrangestore),
    Zrevrange(Zrevrange),
    Zrevrangebylex(Zrevrangebylex),
    Zrevrangebyscore(Zrevrangebyscore),
    Zrevrank(Zrevrank),
    Zrangebyscore(Zrangebyscore),
    Zscan(Zscan),
    Zmscore(Zmscore),
    Zunion(Zunion),
    Zunionstore(Zunionstore),
    Xadd(Xadd),
    Xack(Xack),
    Xackdel(Xackdel),
    Xautoclaim(Xautoclaim),
    Xcfgset(Xcfgset),
    Xclaim(Xclaim),
    Xdel(Xdel),
    Xdelex(Xdelex),
    Xgroup(Xgroup),
    Xinfo(Xinfo),
    Xlen(Xlen),
    Xpending(Xpending),
    Xrange(Xrange),
    Xread(Xread),
    Xreadgroup(Xreadgroup),
    Xrevrange(Xrevrange),
    Xsetid(Xsetid),
    Xtrim(Xtrim),
    Incrby(Incrby),
    Decrby(Decrby),
    Echo(Echo),
    ExpireAt(ExpireAt),
    RandomKey(RandomKey),
    PexpireAt(PexpireAt),
    PexpireTime(PexpireTime),
    Pexpire(Pexpire),
    Psetex(Psetex),
    Lrange(Lrange),
    Bgsave(Bgsave),
    Save(Save),
    GetSet(GetSet),
    Info(Info),
    Move(Move),
    Smismember(Smismember),
    Srandmember(Srandmember),
    Sscan(Sscan),
    Touch(Touch),
    Unlink(Unlink),
    // 事务命令
    Multi(Multi),
    Discard(Discard),
    Exec(Exec),
    Watch(Watch),
    Unwatch(Unwatch),
    Wasm(WasmCommand),
    Lua(LuaCommand),
    VAdd(VAdd),
    VSim(VSim),
    VRem(VRem),
    VCard(VCard),
    VDim(VDim),
    VEmb(VEmb),
    VGetAttr(VGetAttr),
    VSetAttr(VSetAttr),
    VInfo(VInfo),
    VRandMember(VRandMember),
    VLinks(VLinks),
    JsonSet(JsonSet),
    JsonGet(JsonGet),
    JsonDel(JsonDel),
    JsonType(JsonType),
}
impl Command {
    pub fn name(&self) -> &'static str {
        match self {
            Command::Auth(_) => "AUTH",
            Command::Append(_) => "APPEND",
            Command::Bitcount(_) => "BITCOUNT",
            Command::Bitfield(_) => "BITFIELD",
            Command::Bitop(_) => "BITOP",
            Command::Bitpos(_) => "BITPOS",
            Command::Client(_) => "CLIENT",
            Command::Config(_) => "CONFIG",
            Command::Copy(_) => "COPY",
            Command::Dbsize(_) => "DBSIZE",
            Command::Expire(_) => "EXPIRE",
            Command::ExpireTime(_) => "EXPIRETIME",
            Command::Del(_) => "DEL",
            Command::Keys(_) => "KEYS",
            Command::Flushdb(_) => "FLUSHDB",
            Command::Get(_) => "GET",
            Command::Geoadd(_) => "GEOADD",
            Command::Geodist(_) => "GEODIST",
            Command::Geohash(_) => "GEOHASH",
            Command::Geopos(_) => "GEOPOS",
            Command::Georadius(_) => "GEORADIUS",
            Command::Georadiusbymember(_) => "GEORADIUSBYMEMBER",
            Command::Geosearch(_) => "GEOSEARCH",
            Command::Geosearchstore(_) => "GEOSEARCHSTORE",
            Command::Getbit(_) => "GETBIT",
            Command::GetDel(_) => "GETDEL",
            Command::GetEx(_) => "GETEX",
            Command::GetRange(_) => "GETRANGE",
            Command::Lcs(_) => "LCS",
            Command::Ping(_) => "PING",
            Command::Pfadd(_) => "PFADD",
            Command::Pfcount(_) => "PFCOUNT",
            Command::Pfmerge(_) => "PFMERGE",
            Command::Pttl(_) => "PTTL",
            Command::Scan(_) => "SCAN",
            Command::Select(_) => "SELECT",
            Command::Set(_) => "SET",
            Command::Setbit(_) => "SETBIT",
            Command::Setex(_) => "SETEX",
            Command::Setnx(_) => "SETNX",
            Command::SetRange(_) => "SETRANGE",
            Command::Ttl(_) => "TTL",
            Command::Unknown(_) => "UNKNOWN",
            Command::Mset(_) => "MSET",
            Command::Msetex(_) => "MSETEX",
            Command::Msetnx(_) => "MSETNX",
            Command::Mget(_) => "MGET",
            Command::Strlen(_) => "STRLEN",
            Command::Sunionstore(_) => "SUNIONSTORE",
            Command::Renamenx(_) => "RENAMENX",
            Command::Rename(_) => "RENAME",
            Command::Exists(_) => "EXISTS",
            Command::Hset(_) => "HSET",
            Command::Hexpire(_) => "HEXPIRE",
            Command::HexpireAt(_) => "HEXPIREAT",
            Command::HexpireTime(_) => "HEXPIRETIME",
            Command::Hgetdel(_) => "HGETDEL",
            Command::Hgetex(_) => "HGETEX",
            Command::Hpersist(_) => "HPERSIST",
            Command::Hpexpire(_) => "HPEXPIRE",
            Command::HpexpireAt(_) => "HPEXPIREAT",
            Command::HpexpireTime(_) => "HPEXPIRETIME",
            Command::Hpttl(_) => "HPTTL",
            Command::Hincrby(_) => "HINCRBY",
            Command::HincrbyFloat(_) => "HINCRBYFLOAT",
            Command::Hget(_) => "HGET",
            Command::Type(_) => "TYPE",
            Command::Hmset(_) => "HMSET",
            Command::Hexists(_) => "HEXISTS",
            Command::Hstrlen(_) => "HSTRLEN",
            Command::Hmget(_) => "HMGET",
            Command::Hdel(_) => "HDEL",
            Command::Hlen(_) => "HLEN",
            Command::Hscan(_) => "HSCAN",
            Command::Hrandfield(_) => "HRANDFIELD",
            Command::Hsetnx(_) => "HSETNX",
            Command::Hsetex(_) => "HSETEX",
            Command::Hgetall(_) => "HGETALL",
            Command::Httl(_) => "HTTL",
            Command::Hkeys(_) => "HKEYS",
            Command::Blmove(_) => "BLMOVE",
            Command::Blmpop(_) => "BLMPOP",
            Command::Blpop(_) => "BLPOP",
            Command::Brpop(_) => "BRPOP",
            Command::Brpoplpush(_) => "BRPOPLPUSH",
            Command::Lindex(_) => "LINDEX",
            Command::Linsert(_) => "LINSERT",
            Command::Persist(_) => "PERSIST",
            Command::Lmove(_) => "LMOVE",
            Command::Rpop(_) => "RPOP",
            Command::Rpoplpush(_) => "RPOPLPUSH",
            Command::Lpop(_) => "LPOP",
            Command::Lpos(_) => "LPOS",
            Command::Llen(_) => "LLEN",
            Command::Lrem(_) => "LREM",
            Command::Hvals(_) => "HVALS",
            Command::Rpush(_) => "RPUSH",
            Command::Lmpop(_) => "LMPOP",
            Command::Lpush(_) => "LPUSH",
            Command::Sadd(_) => "SADD",
            Command::Sismember(_) => "SISMEMBER",
            Command::Smembers(_) => "SMEMBERS",
            Command::Scard(_) => "SCARD",
            Command::Sdiff(_) => "SDIFF",
            Command::Sdiffstore(_) => "SDIFFSTORE",
            Command::Sinter(_) => "SINTER",
            Command::Sintercard(_) => "SINTERCARD",
            Command::Sinterstore(_) => "SINTERSTORE",
            Command::Smove(_) => "SMOVE",
            Command::Spop(_) => "SPOP",
            Command::Srem(_) => "SREM",
            Command::Flushall(_) => "FLUSHALL",
            Command::FtCreate(_) => "FT.CREATE",
            Command::FtList(_) => "FT._LIST",
            Command::FtDropIndex(_) => "FT.DROPINDEX",
            Command::FtAlter(_) => "FT.ALTER",
            Command::FtAliasAdd(_) => "FT.ALIASADD",
            Command::FtAliasUpdate(_) => "FT.ALIASUPDATE",
            Command::FtAliasDel(_) => "FT.ALIASDEL",
            Command::FtConfig(_) => "FT.CONFIG",
            Command::FtInfo(_) => "FT.INFO",
            Command::FtSearch(_) => "FT.SEARCH",
            Command::FtHybrid(_) => "FT.HYBRID",
            Command::FtAggregate(_) => "FT.AGGREGATE",
            Command::FtCursor(_) => "FT.CURSOR",
            Command::FtProfile(_) => "FT.PROFILE",
            Command::FtExplain(_) => "FT.EXPLAIN",
            Command::FtTagVals(_) => "FT.TAGVALS",
            Command::FtDict(_) => "FT.DICT",
            Command::FtSpellCheck(_) => "FT.SPELLCHECK",
            Command::FtSug(_) => "FT.SUG",
            Command::FtSyn(_) => "FT.SYN",
            Command::FtUnsupported(_) => "FT.UNSUPPORTED",
            Command::Lpushx(_) => "LPUSHX",
            Command::Rpushx(_) => "RPUSHX",
            Command::Decr(_) => "DECR",
            Command::Incr(_) => "INCR",
            Command::IncrbyFloat(_) => "INCRBYFLOAT",
            Command::Lset(_) => "LSET",
            Command::Ltrim(_) => "LTRIM",
            Command::Sunion(_) => "SUNION",
            Command::Bzmpop(_) => "BZMPOP",
            Command::Bzpopmax(_) => "BZPOPMAX",
            Command::Bzpopmin(_) => "BZPOPMIN",
            Command::Zcount(_) => "ZCOUNT",
            Command::Zadd(_) => "ZADD",
            Command::Zdiff(_) => "ZDIFF",
            Command::Zdiffstore(_) => "ZDIFFSTORE",
            Command::Zincrby(_) => "ZINCRBY",
            Command::Zinter(_) => "ZINTER",
            Command::Zintercard(_) => "ZINTERCARD",
            Command::Zinterstore(_) => "ZINTERSTORE",
            Command::Zlexcount(_) => "ZLEXCOUNT",
            Command::Zmpop(_) => "ZMPOP",
            Command::Zscore(_) => "ZSCORE",
            Command::Zcard(_) => "ZCARD",
            Command::Zpopmax(_) => "ZPOPMAX",
            Command::Zpopmin(_) => "ZPOPMIN",
            Command::Zrandmember(_) => "ZRANDMEMBER",
            Command::Zrank(_) => "ZRANK",
            Command::Zrem(_) => "ZREM",
            Command::Zremrangebylex(_) => "ZREMRANGEBYLEX",
            Command::Zremrangebyrank(_) => "ZREMRANGEBYRANK",
            Command::Zremrangebyscore(_) => "ZREMRANGEBYSCORE",
            Command::Zrange(_) => "ZRANGE",
            Command::Zrangebylex(_) => "ZRANGEBYLEX",
            Command::Zrangestore(_) => "ZRANGESTORE",
            Command::Zrevrange(_) => "ZREVRANGE",
            Command::Zrevrangebylex(_) => "ZREVRANGEBYLEX",
            Command::Zrevrangebyscore(_) => "ZREVRANGEBYSCORE",
            Command::Zrevrank(_) => "ZREVRANK",
            Command::Zrangebyscore(_) => "ZRANGEBYSCORE",
            Command::Zscan(_) => "ZSCAN",
            Command::Zmscore(_) => "ZMSCORE",
            Command::Zunion(_) => "ZUNION",
            Command::Zunionstore(_) => "ZUNIONSTORE",
            Command::Xadd(_) => "XADD",
            Command::Xack(_) => "XACK",
            Command::Xackdel(_) => "XACKDEL",
            Command::Xautoclaim(_) => "XAUTOCLAIM",
            Command::Xcfgset(_) => "XCFGSET",
            Command::Xclaim(_) => "XCLAIM",
            Command::Xdel(_) => "XDEL",
            Command::Xdelex(_) => "XDELEX",
            Command::Xgroup(_) => "XGROUP",
            Command::Xinfo(_) => "XINFO",
            Command::Xlen(_) => "XLEN",
            Command::Xpending(_) => "XPENDING",
            Command::Xrange(_) => "XRANGE",
            Command::Xread(_) => "XREAD",
            Command::Xreadgroup(_) => "XREADGROUP",
            Command::Xrevrange(_) => "XREVRANGE",
            Command::Xsetid(_) => "XSETID",
            Command::Xtrim(_) => "XTRIM",
            Command::Incrby(_) => "INCRBY",
            Command::Decrby(_) => "DECRBY",
            Command::Echo(_) => "ECHO",
            Command::ExpireAt(_) => "EXPIREAT",
            Command::RandomKey(_) => "RANDOMKEY",
            Command::PexpireAt(_) => "PEXPIREAT",
            Command::PexpireTime(_) => "PEXPIRETIME",
            Command::Pexpire(_) => "PEXPIRE",
            Command::Psetex(_) => "PSETEX",
            Command::Lrange(_) => "LRANGE",
            Command::Bgsave(_) => "BGSAVE",
            Command::Save(_) => "SAVE",
            Command::GetSet(_) => "GETSET",
            Command::Info(_) => "INFO",
            Command::Move(_) => "MOVE",
            Command::Smismember(_) => "SMISMEMBER",
            Command::Srandmember(_) => "SRANDMEMBER",
            Command::Sscan(_) => "SSCAN",
            Command::Touch(_) => "TOUCH",
            Command::Unlink(_) => "UNLINK",
            Command::Multi(_) => "MULTI",
            Command::Discard(_) => "DISCARD",
            Command::Exec(_) => "EXEC",
            Command::Watch(_) => "WATCH",
            Command::Unwatch(_) => "UNWATCH",
            Command::Wasm(_) => "WASM",
            Command::Lua(_) => "LUA",
            Command::VAdd(_) => "VADD",
            Command::VSim(_) => "VSIM",
            Command::VRem(_) => "VREM",
            Command::VCard(_) => "VCARD",
            Command::VDim(_) => "VDIM",
            Command::VEmb(_) => "VEMB",
            Command::VGetAttr(_) => "VGETATTR",
            Command::VSetAttr(_) => "VSETATTR",
            Command::VInfo(_) => "VINFO",
            Command::VRandMember(_) => "VRANDMEMBER",
            Command::VLinks(_) => "VLINKS",
            Command::JsonSet(_) => "JSON.SET",
            Command::JsonGet(_) => "JSON.GET",
            Command::JsonDel(_) => "JSON.DEL",
            Command::JsonType(_) => "JSON.TYPE",
        }
    }

    pub fn parse_from_frame(frame: Frame) -> Result<Self, Error> {
        let command_name = frame
            .get_arg(0)
            .ok_or_else(|| Error::msg("ERR empty command"))?;
        let command = match command_name.to_uppercase().as_str() {
            "AUTH" => Command::Auth(Auth::parse_from_frame(frame)?),
            "BITCOUNT" => Command::Bitcount(Bitcount::parse_from_frame(frame)?),
            "BITFIELD" => Command::Bitfield(Bitfield::parse_from_frame(frame)?),
            "BITFIELD_RO" => Command::Bitfield(Bitfield::parse_ro_from_frame(frame)?),
            "BITOP" => Command::Bitop(Bitop::parse_from_frame(frame)?),
            "BITPOS" => Command::Bitpos(Bitpos::parse_from_frame(frame)?),
            "COPY" => Command::Copy(Copy::parse_from_frame(frame)?),
            "DEL" => Command::Del(Del::parse_from_frame(frame)?),
            "EXPIRE" => Command::Expire(Expire::parse_from_frame(frame)?),
            "EXPIRETIME" => Command::ExpireTime(ExpireTime::parse_from_frame(frame)?),
            "FLUSHALL" => Command::Flushall(Flushall::parse_from_frame(frame)?),
            "FLUSHDB" => Command::Flushdb(Flushdb::parse_from_frame(frame)?),
            "FT.CREATE" => Command::FtCreate(FtCreate::parse_from_frame(frame)?),
            "FT._LIST" => Command::FtList(FtList::parse_from_frame(frame)?),
            "FT.DROPINDEX" => Command::FtDropIndex(FtDropIndex::parse_from_frame(frame)?),
            "FT.ALTER" => Command::FtAlter(FtAlter::parse_from_frame(frame)?),
            "FT.ALIASADD" => Command::FtAliasAdd(FtAliasAdd::parse_from_frame(frame)?),
            "FT.ALIASUPDATE" => Command::FtAliasUpdate(FtAliasUpdate::parse_from_frame(frame)?),
            "FT.ALIASDEL" => Command::FtAliasDel(FtAliasDel::parse_from_frame(frame)?),
            "FT.CONFIG" => Command::FtConfig(FtConfig::parse_from_frame(frame)?),
            "FT.INFO" => Command::FtInfo(FtInfo::parse_from_frame(frame)?),
            "FT.SEARCH" => Command::FtSearch(FtSearch::parse_from_frame(frame)?),
            "FT.HYBRID" => Command::FtHybrid(FtHybrid::parse_from_frame(frame)?),
            "FT.AGGREGATE" => Command::FtAggregate(FtAggregate::parse_from_frame(frame)?),
            "FT.CURSOR" => Command::FtCursor(FtCursor::parse_from_frame(frame)?),
            "FT.PROFILE" => Command::FtProfile(FtProfile::parse_from_frame(frame)?),
            "FT.EXPLAIN" | "FT.EXPLAINCLI" => {
                Command::FtExplain(FtExplain::parse_from_frame(frame)?)
            }
            "FT.TAGVALS" => Command::FtTagVals(FtTagVals::parse_from_frame(frame)?),
            "FT.DICTADD" | "FT.DICTDEL" | "FT.DICTDUMP" => {
                Command::FtDict(FtDict::parse_from_frame(frame)?)
            }
            "FT.SPELLCHECK" => Command::FtSpellCheck(FtSpellCheck::parse_from_frame(frame)?),
            "FT.SUGADD" | "FT.SUGDEL" | "FT.SUGGET" | "FT.SUGLEN" => {
                Command::FtSug(FtSug::parse_from_frame(frame)?)
            }
            "FT.SYNDUMP" | "FT.SYNUPDATE" => Command::FtSyn(FtSyn::parse_from_frame(frame)?),
            "GETRANGE" | "SUBSTR" => Command::GetRange(GetRange::parse_from_frame(frame)?),
            "GETDEL" => Command::GetDel(GetDel::parse_from_frame(frame)?),
            "GETEX" => Command::GetEx(GetEx::parse_from_frame(frame)?),
            "GET" => Command::Get(Get::parse_from_frame(frame)?),
            "LCS" => Command::Lcs(Lcs::parse_from_frame(frame)?),
            "GEOADD" => Command::Geoadd(Geoadd::parse_from_frame(frame)?),
            "GEODIST" => Command::Geodist(Geodist::parse_from_frame(frame)?),
            "GEOHASH" => Command::Geohash(Geohash::parse_from_frame(frame)?),
            "GEOPOS" => Command::Geopos(Geopos::parse_from_frame(frame)?),
            "GEORADIUS" | "GEORADIUS_RO" => {
                Command::Georadius(Geosearch::parse_georadius_from_frame(frame)?)
            }
            "GEORADIUSBYMEMBER" | "GEORADIUSBYMEMBER_RO" => {
                Command::Georadiusbymember(Geosearch::parse_georadiusbymember_from_frame(frame)?)
            }
            "GEOSEARCH" => Command::Geosearch(Geosearch::parse_from_frame(frame)?),
            "GEOSEARCHSTORE" => Command::Geosearchstore(Geosearchstore::parse_from_frame(frame)?),
            "GETBIT" => Command::Getbit(Getbit::parse_from_frame(frame)?),
            "PING" => Command::Ping(Ping::parse_from_frame(frame)?),
            "PFADD" => Command::Pfadd(Pfadd::parse_from_frame(frame)?),
            "PFCOUNT" => Command::Pfcount(Pfcount::parse_from_frame(frame)?),
            "PFMERGE" => Command::Pfmerge(Pfmerge::parse_from_frame(frame)?),
            "PTTL" => Command::Pttl(Pttl::parse_from_frame(frame)?),
            "TYPE" => Command::Type(Type::parse_from_frame(frame)?),
            "SELECT" => Command::Select(Select::parse_from_frame(frame)?),
            "SET" => Command::Set(Set::parse_from_frame(frame)?),
            "SETBIT" => Command::Setbit(Setbit::parse_from_frame(frame)?),
            "SETEX" => Command::Setex(Setex::parse_from_frame(frame)?),
            "SETNX" => Command::Setnx(Setnx::parse_from_frame(frame)?),
            "SETRANGE" => Command::SetRange(SetRange::parse_from_frame(frame)?),
            "TTL" => Command::Ttl(Ttl::parse_from_frame(frame)?),
            "RANDOMKEY" => Command::RandomKey(RandomKey::parse_from_frame(frame)?),
            "RENAME" => Command::Rename(Rename::parse_from_frame(frame)?),
            "EXISTS" => Command::Exists(Exists::parse_from_frame(frame)?),
            "STRLEN" => Command::Strlen(Strlen::parse_from_frame(frame)?),
            "MSET" => Command::Mset(Mset::parse_from_frame(frame)?),
            "MSETEX" => Command::Msetex(Msetex::parse_from_frame(frame)?),
            "MSETNX" => Command::Msetnx(Msetnx::parse_from_frame(frame)?),
            "MGET" => Command::Mget(Mget::parse_from_frame(frame)?),
            "APPEND" => Command::Append(Append::parse_from_frame(frame)?),
            "DBSIZE" => Command::Dbsize(Dbsize::parse_from_frame(frame)?),
            "HSET" => Command::Hset(Hset::parse_from_frame(frame)?),
            "HEXPIRE" => Command::Hexpire(Hexpire::parse_from_frame(frame, false, false)?),
            "HEXPIREAT" => Command::HexpireAt(Hexpire::parse_from_frame(frame, false, true)?),
            "HEXPIRETIME" => Command::HexpireTime(Httl::parse_from_frame(frame, false, true)?),
            "HGET" => Command::Hget(Hget::parse_from_frame(frame)?),
            "HGETDEL" => Command::Hgetdel(Hgetdel::parse_from_frame(frame)?),
            "HGETEX" => Command::Hgetex(Hgetex::parse_from_frame(frame)?),
            "HINCRBY" => Command::Hincrby(Hincrby::parse_from_frame(frame)?),
            "HINCRBYFLOAT" => Command::HincrbyFloat(HincrbyFloat::parse_from_frame(frame)?),
            "HMSET" => Command::Hmset(Hmset::parse_from_frame(frame)?),
            "HPERSIST" => Command::Hpersist(Hpersist::parse_from_frame(frame)?),
            "HPEXPIRE" => Command::Hpexpire(Hexpire::parse_from_frame(frame, true, false)?),
            "HPEXPIREAT" => Command::HpexpireAt(Hexpire::parse_from_frame(frame, true, true)?),
            "HPEXPIRETIME" => Command::HpexpireTime(Httl::parse_from_frame(frame, true, true)?),
            "HPTTL" => Command::Hpttl(Httl::parse_from_frame(frame, true, false)?),
            "HDEL" => Command::Hdel(Hdel::parse_from_frame(frame)?),
            "HEXISTS" => Command::Hexists(Hexists::parse_from_frame(frame)?),
            "HSTRLEN" => Command::Hstrlen(Hstrlen::parse_from_frame(frame)?),
            "KEYS" => Command::Keys(Keys::parse_from_frame(frame)?),
            "HMGET" => Command::Hmget(Hmget::parse_from_frame(frame)?),
            "HLEN" => Command::Hlen(Hlen::parse_from_frame(frame)?),
            "HSCAN" => Command::Hscan(Hscan::parse_from_frame(frame)?),
            "HRANDFIELD" => Command::Hrandfield(Hrandfield::parse_from_frame(frame)?),
            "HGETALL" => Command::Hgetall(Hgetall::parse_from_frame(frame)?),
            "HSETEX" => Command::Hsetex(Hsetex::parse_from_frame(frame)?),
            "HSETNX" => Command::Hsetnx(Hsetnx::parse_from_frame(frame)?),
            "HTTL" => Command::Httl(Httl::parse_from_frame(frame, false, false)?),
            "HKEYS" => Command::Hkeys(Hkeys::parse_from_frame(frame)?),
            "BLMOVE" => Command::Blmove(Blmove::parse_from_frame(frame)?),
            "BLMPOP" => Command::Blmpop(Blmpop::parse_from_frame(frame)?),
            "BLPOP" => Command::Blpop(Blpop::parse_from_frame(frame)?),
            "BRPOP" => Command::Brpop(Brpop::parse_from_frame(frame)?),
            "BRPOPLPUSH" => Command::Brpoplpush(Brpoplpush::parse_from_frame(frame)?),
            "PERSIST" => Command::Persist(Persist::parse_from_frame(frame)?),
            "LINDEX" => Command::Lindex(Lindex::parse_from_frame(frame)?),
            "LINSERT" => Command::Linsert(Linsert::parse_from_frame(frame)?),
            "LMOVE" => Command::Lmove(Lmove::parse_from_frame(frame)?),
            "RPOP" => Command::Rpop(Rpop::parse_from_frame(frame)?),
            "RPOPLPUSH" => Command::Rpoplpush(Rpoplpush::parse_from_frame(frame)?),
            "LPOP" => Command::Lpop(Lpop::parse_from_frame(frame)?),
            "LPOS" => Command::Lpos(Lpos::parse_from_frame(frame)?),
            "LREM" => Command::Lrem(Lrem::parse_from_frame(frame)?),
            "LLEN" => Command::Llen(Llen::parse_from_frame(frame)?),
            "HVALS" => Command::Hvals(Hvals::parse_from_frame(frame)?),
            "RPUSH" => Command::Rpush(Rpush::parse_from_frame(frame)?),
            "LMPOP" => Command::Lmpop(Lmpop::parse_from_frame(frame)?),
            "LPUSH" => Command::Lpush(Lpush::parse_from_frame(frame)?),
            "SADD" => Command::Sadd(Sadd::parse_from_frame(frame)?),
            "SCARD" => Command::Scard(Scard::parse_from_frame(frame)?),
            "RENAMENX" => Command::Renamenx(Renamenx::parse_from_frame(frame)?),
            "EXPIREAT" => Command::ExpireAt(ExpireAt::parse_from_frame(frame)?),
            "SUNIONSTORE" => Command::Sunionstore(Sunionstore::parse_from_frame(frame)?),
            "SISMEMBER" => Command::Sismember(Sismember::parse_from_frame(frame)?),
            "SMEMBERS" => Command::Smembers(Smembers::parse_from_frame(frame)?),
            "SPOP" => Command::Spop(Spop::parse_from_frame(frame)?),
            "SREM" => Command::Srem(Srem::parse_from_frame(frame)?),
            "LPUSHX" => Command::Lpushx(Lpushx::parse_from_frame(frame)?),
            "RPUSHX" => Command::Rpushx(Rpushx::parse_from_frame(frame)?),
            "INCR" => Command::Incr(Incr::parse_from_frame(frame)?),
            "DECR" => Command::Decr(Decr::parse_from_frame(frame)?),
            "LSET" => Command::Lset(Lset::parse_from_frame(frame)?),
            "LTRIM" => Command::Ltrim(Ltrim::parse_from_frame(frame)?),
            "SUNION" => Command::Sunion(Sunion::parse_from_frame(frame)?),
            "BZMPOP" => Command::Bzmpop(Bzmpop::parse_from_frame(frame)?),
            "BZPOPMAX" => Command::Bzpopmax(Bzpopmax::parse_from_frame(frame)?),
            "BZPOPMIN" => Command::Bzpopmin(Bzpopmin::parse_from_frame(frame)?),
            "ZCOUNT" => Command::Zcount(Zcount::parse_from_frame(frame)?),
            "ZADD" => Command::Zadd(Zadd::parse_from_frame(frame)?),
            "ZDIFF" => Command::Zdiff(Zdiff::parse_from_frame(frame)?),
            "ZDIFFSTORE" => Command::Zdiffstore(Zdiffstore::parse_from_frame(frame)?),
            "ZCARD" => Command::Zcard(Zcard::parse_from_frame(frame)?),
            "ZINTER" => Command::Zinter(Zinter::parse_from_frame(frame)?),
            "ZINTERCARD" => Command::Zintercard(Zintercard::parse_from_frame(frame)?),
            "ZINTERSTORE" => Command::Zinterstore(Zinterstore::parse_from_frame(frame)?),
            "ZLEXCOUNT" => Command::Zlexcount(Zlexcount::parse_from_frame(frame)?),
            "ZMPOP" => Command::Zmpop(Zmpop::parse_from_frame(frame)?),
            "ZPOPMAX" => Command::Zpopmax(Zpopmax::parse_from_frame(frame)?),
            "ZPOPMIN" => Command::Zpopmin(Zpopmin::parse_from_frame(frame)?),
            "ZRANDMEMBER" => Command::Zrandmember(Zrandmember::parse_from_frame(frame)?),
            "ZSCORE" => Command::Zscore(Zscore::parse_from_frame(frame)?),
            "ZREM" => Command::Zrem(Zrem::parse_from_frame(frame)?),
            "ZREMRANGEBYLEX" => Command::Zremrangebylex(Zremrangebylex::parse_from_frame(frame)?),
            "ZREMRANGEBYRANK" => {
                Command::Zremrangebyrank(Zremrangebyrank::parse_from_frame(frame)?)
            }
            "ZREMRANGEBYSCORE" => {
                Command::Zremrangebyscore(Zremrangebyscore::parse_from_frame(frame)?)
            }
            "ZRANGE" => Command::Zrange(Zrange::parse_from_frame(frame)?),
            "ZRANGEBYLEX" => Command::Zrangebylex(Zrangebylex::parse_from_frame(frame)?),
            "ZREVRANGE" => Command::Zrevrange(Zrevrange::parse_from_frame(frame)?),
            "ZREVRANGEBYLEX" => Command::Zrevrangebylex(Zrevrangebylex::parse_from_frame(frame)?),
            "ZREVRANGEBYSCORE" => {
                Command::Zrevrangebyscore(Zrevrangebyscore::parse_from_frame(frame)?)
            }
            "ZREVRANK" => Command::Zrevrank(Zrevrank::parse_from_frame(frame)?),
            "ZRANGEBYSCORE" => Command::Zrangebyscore(Zrangebyscore::parse_from_frame(frame)?),
            "ZRANGESTORE" => Command::Zrangestore(Zrangestore::parse_from_frame(frame)?),
            "ZMSCORE" => Command::Zmscore(Zmscore::parse_from_frame(frame)?),
            "ZUNION" => Command::Zunion(Zunion::parse_from_frame(frame)?),
            "ZUNIONSTORE" => Command::Zunionstore(Zunionstore::parse_from_frame(frame)?),
            "SDIFF" => Command::Sdiff(Sdiff::parse_from_frame(frame)?),
            "SDIFFSTORE" => Command::Sdiffstore(Sdiffstore::parse_from_frame(frame)?),
            "SINTER" => Command::Sinter(Sinter::parse_from_frame(frame)?),
            "SINTERCARD" => Command::Sintercard(Sintercard::parse_from_frame(frame)?),
            "SINTERSTORE" => Command::Sinterstore(Sinterstore::parse_from_frame(frame)?),
            "SMISMEMBER" => Command::Smismember(Smismember::parse_from_frame(frame)?),
            "SMOVE" => Command::Smove(Smove::parse_from_frame(frame)?),
            "SRANDMEMBER" => Command::Srandmember(Srandmember::parse_from_frame(frame)?),
            "ZRANK" => Command::Zrank(Zrank::parse_from_frame(frame)?),
            "ZINCRBY" => Command::Zincrby(Zincrby::parse_from_frame(frame)?),
            "INCRBY" => Command::Incrby(Incrby::parse_from_frame(frame)?),
            "INCRBYFLOAT" => Command::IncrbyFloat(IncrbyFloat::parse_from_frame(frame)?),
            "DECRBY" => Command::Decrby(Decrby::parse_from_frame(frame)?),
            "ECHO" => Command::Echo(Echo::parse_from_frame(frame)?),
            "PEXPIRE" => Command::Pexpire(Pexpire::parse_from_frame(frame)?),
            "PSETEX" => Command::Psetex(Psetex::parse_from_frame(frame)?),
            "PEXPIREAT" => Command::PexpireAt(PexpireAt::parse_from_frame(frame)?),
            "PEXPIRETIME" => Command::PexpireTime(PexpireTime::parse_from_frame(frame)?),
            "LRANGE" => Command::Lrange(Lrange::parse_from_frame(frame)?),
            "GETSET" => Command::GetSet(GetSet::parse_from_frame(frame)?),
            "CLIENT" => Command::Client(Client::parse_from_frame(frame)?),
            "CONFIG" => Command::Config(Config::parse_from_frame(frame)?),
            "INFO" => Command::Info(Info::parse_from_frame(frame)?),
            "BGSAVE" => Command::Bgsave(Bgsave::parse_from_frame(frame)?),
            "SAVE" => Command::Save(Save::parse_from_frame(frame)?),
            "MOVE" => Command::Move(Move::parse_from_frame(frame)?),
            "MULTI" => Command::Multi(Multi::parse_from_frame(frame)?),
            "EXEC" => Command::Exec(Exec::parse_from_frame(frame)?),
            "DISCARD" => Command::Discard(Discard::parse_from_frame(frame)?),
            "WATCH" => Command::Watch(Watch::parse_from_frame(frame)?),
            "UNWATCH" => Command::Unwatch(Unwatch::parse_from_frame(frame)?),
            "SCAN" => Command::Scan(Scan::parse_from_frame(frame)?),
            "SSCAN" => Command::Sscan(Sscan::parse_from_frame(frame)?),
            "ZSCAN" => Command::Zscan(Zscan::parse_from_frame(frame)?),
            "XACK" => Command::Xack(Xack::parse_from_frame(frame)?),
            "XACKDEL" => Command::Xackdel(Xackdel::parse_from_frame(frame)?),
            "XADD" => Command::Xadd(Xadd::parse_from_frame(frame)?),
            "XAUTOCLAIM" => Command::Xautoclaim(Xautoclaim::parse_from_frame(frame)?),
            "XCFGSET" => Command::Xcfgset(Xcfgset::parse_from_frame(frame)?),
            "XCLAIM" => Command::Xclaim(Xclaim::parse_from_frame(frame)?),
            "XDEL" => Command::Xdel(Xdel::parse_from_frame(frame)?),
            "XDELEX" => Command::Xdelex(Xdelex::parse_from_frame(frame)?),
            "XGROUP" => Command::Xgroup(Xgroup::parse_from_frame(frame)?),
            "XINFO" => Command::Xinfo(Xinfo::parse_from_frame(frame)?),
            "XLEN" => Command::Xlen(Xlen::parse_from_frame(frame)?),
            "XPENDING" => Command::Xpending(Xpending::parse_from_frame(frame)?),
            "XRANGE" => Command::Xrange(Xrange::parse_from_frame(frame)?),
            "XREAD" => Command::Xread(Xread::parse_from_frame(frame)?),
            "XREADGROUP" => Command::Xreadgroup(Xreadgroup::parse_from_frame(frame)?),
            "XREVRANGE" => Command::Xrevrange(Xrevrange::parse_from_frame(frame)?),
            "XSETID" => Command::Xsetid(Xsetid::parse_from_frame(frame)?),
            "XTRIM" => Command::Xtrim(Xtrim::parse_from_frame(frame)?),
            "TOUCH" => Command::Touch(Touch::parse_from_frame(frame)?),
            "UNLINK" => Command::Unlink(Unlink::parse_from_frame(frame)?),
            "JSON.SET" => Command::JsonSet(JsonSet::parse_from_frame(frame)?),
            "JSON.GET" => Command::JsonGet(JsonGet::parse_from_frame(frame)?),
            "JSON.DEL" => Command::JsonDel(JsonDel::parse_from_frame(frame)?),
            "JSON.TYPE" => Command::JsonType(JsonType::parse_from_frame(frame)?),
            "VADD" => Command::VAdd(VAdd::parse_from_frame(frame)?),
            "VSIM" => Command::VSim(VSim::parse_from_frame(frame)?),
            "VREM" => Command::VRem(VRem::parse_from_frame(frame)?),
            "VCARD" => Command::VCard(VCard::parse_from_frame(frame)?),
            "VDIM" => Command::VDim(VDim::parse_from_frame(frame)?),
            "VEMB" => Command::VEmb(VEmb::parse_from_frame(frame)?),
            "VGETATTR" => Command::VGetAttr(VGetAttr::parse_from_frame(frame)?),
            "VSETATTR" => Command::VSetAttr(VSetAttr::parse_from_frame(frame)?),
            "VINFO" => Command::VInfo(VInfo::parse_from_frame(frame)?),
            "VRANDMEMBER" => Command::VRandMember(VRandMember::parse_from_frame(frame)?),
            "VLINKS" => Command::VLinks(VLinks::parse_from_frame(frame)?),
            "EVAL" | "EVALSHA" | "EVAL_RO" | "EVALSHA_RO" | "SCRIPT" => {
                Command::Lua(LuaCommand::parse_from_frame(frame)?)
            }
            "WASM.LOAD" | "WASM.CALL" | "WASM.CALL_RO" | "WASM.DEL" | "WASM.SCAN" | "WASM.LIST"
            | "FUNCTION" | "FCALL" | "FCALL_RO" => {
                Command::Wasm(WasmCommand::parse_from_frame(frame)?)
            }
            _ => Command::Unknown(Unknown::parse_from_frame(frame)?),
        };
        Ok(command)
    }
    pub fn propagate_aof_if_needed(&self) -> bool {
        match self {
            Command::Del(_)
            | Command::Copy(_)
            | Command::Bitop(_)
            | Command::Bitfield(_)
            | Command::Setbit(_)
            | Command::GetDel(_)
            | Command::GetEx(_)
            | Command::Geoadd(_)
            | Command::Geosearchstore(_)
            | Command::Expire(_)
            | Command::ExpireAt(_)
            | Command::Persist(_)
            | Command::Pexpire(_)
            | Command::PexpireAt(_)
            | Command::Pfadd(_)
            | Command::Pfmerge(_)
            | Command::Rename(_)
            | Command::Renamenx(_)
            | Command::Append(_)
            | Command::Decr(_)
            | Command::Decrby(_)
            | Command::GetSet(_)
            | Command::Incr(_)
            | Command::Incrby(_)
            | Command::IncrbyFloat(_)
            | Command::Mset(_)
            | Command::Msetex(_)
            | Command::Msetnx(_)
            | Command::Set(_)
            | Command::Setex(_)
            | Command::Setnx(_)
            | Command::SetRange(_)
            | Command::Flushall(_)
            | Command::FtCreate(_)
            | Command::Flushdb(_)
            | Command::Blmove(_)
            | Command::Blmpop(_)
            | Command::Blpop(_)
            | Command::Brpop(_)
            | Command::Brpoplpush(_)
            | Command::Hdel(_)
            | Command::Hexpire(_)
            | Command::HexpireAt(_)
            | Command::Hgetdel(_)
            | Command::Hgetex(_)
            | Command::Hincrby(_)
            | Command::HincrbyFloat(_)
            | Command::Hmset(_)
            | Command::Hpersist(_)
            | Command::Hpexpire(_)
            | Command::HpexpireAt(_)
            | Command::Hset(_)
            | Command::Hsetex(_)
            | Command::Hsetnx(_)
            | Command::Linsert(_)
            | Command::Lmpop(_)
            | Command::Lpop(_)
            | Command::Lpush(_)
            | Command::Lpushx(_)
            | Command::Lrem(_)
            | Command::Lset(_)
            | Command::Ltrim(_)
            | Command::Rpop(_)
            | Command::Rpush(_)
            | Command::Rpushx(_)
            | Command::Sadd(_)
            | Command::Sdiffstore(_)
            | Command::Sinterstore(_)
            | Command::Smove(_)
            | Command::Spop(_)
            | Command::Srem(_)
            | Command::Sunionstore(_)
            | Command::Unlink(_)
            | Command::Bzmpop(_)
            | Command::Bzpopmax(_)
            | Command::Bzpopmin(_)
            | Command::Zadd(_)
            | Command::Zdiffstore(_)
            | Command::Zincrby(_)
            | Command::Zinterstore(_)
            | Command::Zmpop(_)
            | Command::Zpopmax(_)
            | Command::Zpopmin(_)
            | Command::Zrangestore(_)
            | Command::Zrem(_)
            | Command::Zremrangebylex(_)
            | Command::Zremrangebyrank(_)
            | Command::Zremrangebyscore(_)
            | Command::Zunionstore(_)
            | Command::Xack(_)
            | Command::Xackdel(_)
            | Command::Xadd(_)
            | Command::Xautoclaim(_)
            | Command::Xclaim(_)
            | Command::Xdel(_)
            | Command::Xdelex(_)
            | Command::Xgroup(_)
            | Command::Xreadgroup(_)
            | Command::Xsetid(_)
            | Command::Xtrim(_)
            | Command::JsonSet(_)
            | Command::JsonDel(_)
            | Command::VAdd(_)
            | Command::VRem(_)
            | Command::VSetAttr(_)
            | Command::Lua(_)
            | Command::Psetex(_)
            | Command::Move(_) => true,
            _ => false,
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    fn frame_args(args: &[&str]) -> Frame {
        Frame::Array(
            args.iter()
                .map(|arg| Frame::BulkString(arg.as_bytes().to_vec()))
                .collect(),
        )
    }

    #[test]
    fn parse_dispatch_covers_aliases_and_extension_command_families() {
        let known_commands = [
            "BITFIELD_RO",
            "FT.CREATE",
            "FT._LIST",
            "FT.DROPINDEX",
            "FT.ALTER",
            "FT.ALIASADD",
            "FT.ALIASUPDATE",
            "FT.ALIASDEL",
            "FT.CONFIG",
            "FT.INFO",
            "FT.SEARCH",
            "FT.HYBRID",
            "FT.AGGREGATE",
            "FT.CURSOR",
            "FT.PROFILE",
            "FT.EXPLAIN",
            "FT.EXPLAINCLI",
            "FT.TAGVALS",
            "FT.DICTADD",
            "FT.DICTDEL",
            "FT.DICTDUMP",
            "FT.SPELLCHECK",
            "FT.SUGADD",
            "FT.SUGDEL",
            "FT.SUGGET",
            "FT.SUGLEN",
            "FT.SYNDUMP",
            "FT.SYNUPDATE",
            "GEORADIUS_RO",
            "GEORADIUSBYMEMBER_RO",
            "SUBSTR",
            "XACK",
            "XACKDEL",
            "XADD",
            "XAUTOCLAIM",
            "XCFGSET",
            "XCLAIM",
            "XDEL",
            "XDELEX",
            "XGROUP",
            "XINFO",
            "XLEN",
            "XPENDING",
            "XRANGE",
            "XREAD",
            "XREADGROUP",
            "XREVRANGE",
            "XSETID",
            "XTRIM",
            "EVAL",
            "EVALSHA",
            "EVAL_RO",
            "EVALSHA_RO",
            "SCRIPT",
            "WASM.LOAD",
            "WASM.CALL",
            "WASM.CALL_RO",
            "WASM.DEL",
            "WASM.SCAN",
            "WASM.LIST",
            "FUNCTION",
            "FCALL",
            "FCALL_RO",
        ];

        for command_name in known_commands {
            let parsed = Command::parse_from_frame(frame_args(&[command_name]));
            if let Ok(command) = parsed {
                assert_ne!(command.name(), "UNKNOWN", "{command_name}");
            }
        }
    }

    #[test]
    fn parse_dispatch_reports_empty_and_unknown_commands() {
        assert!(Command::parse_from_frame(Frame::Array(Vec::new())).is_err());
        assert!(matches!(
            Command::parse_from_frame(frame_args(&["definitely-not-redis"])).unwrap(),
            Command::Unknown(_)
        ));
    }

    #[test]
    fn command_name_and_aof_flags_cover_late_dispatch_variants() {
        let cases: &[(&[&str], &str, bool)] = &[
            (&["CLIENT", "HELP"], "CLIENT", false),
            (&["CONFIG", "HELP"], "CONFIG", false),
            (&["SADD", "s", "a"], "SADD", true),
            (&["SISMEMBER", "s", "a"], "SISMEMBER", false),
            (&["SMEMBERS", "s"], "SMEMBERS", false),
            (&["SCARD", "s"], "SCARD", false),
            (&["SDIFF", "s"], "SDIFF", false),
            (&["SDIFFSTORE", "dst", "s"], "SDIFFSTORE", true),
            (&["SINTER", "s"], "SINTER", false),
            (&["SINTERCARD", "1", "s"], "SINTERCARD", false),
            (&["SINTERSTORE", "dst", "s"], "SINTERSTORE", true),
            (&["SMOVE", "s", "dst", "a"], "SMOVE", true),
            (&["SPOP", "s"], "SPOP", true),
            (&["SREM", "s", "a"], "SREM", true),
            (&["FLUSHALL"], "FLUSHALL", true),
            (
                &["FT.CREATE", "idx", "ON", "HASH", "SCHEMA", "title", "TEXT"],
                "FT.CREATE",
                true,
            ),
            (&["FT._LIST"], "FT._LIST", false),
            (&["FT.DROPINDEX", "idx"], "FT.DROPINDEX", false),
            (
                &["FT.ALTER", "idx", "SCHEMA", "ADD", "body", "TEXT"],
                "FT.ALTER",
                false,
            ),
            (&["FT.ALIASADD", "alias", "idx"], "FT.ALIASADD", false),
            (&["FT.ALIASUPDATE", "alias", "idx"], "FT.ALIASUPDATE", false),
            (&["FT.ALIASDEL", "alias"], "FT.ALIASDEL", false),
            (&["FT.CONFIG", "GET", "DEFAULT_DIALECT"], "FT.CONFIG", false),
            (&["FT.INFO", "idx"], "FT.INFO", false),
            (&["FT.SEARCH", "idx", "*"], "FT.SEARCH", false),
            (
                &[
                    "FT.HYBRID",
                    "idx",
                    "*=>[KNN 1 @v $BLOB]",
                    "PARAMS",
                    "2",
                    "BLOB",
                    "[1,0]",
                ],
                "FT.HYBRID",
                false,
            ),
            (&["FT.AGGREGATE", "idx", "*"], "FT.AGGREGATE", false),
            (&["FT.CURSOR", "READ", "idx", "1"], "FT.CURSOR", false),
            (
                &["FT.PROFILE", "idx", "SEARCH", "QUERY", "*", "NOCONTENT"],
                "FT.PROFILE",
                false,
            ),
            (&["FT.EXPLAIN", "idx", "*"], "FT.EXPLAIN", false),
            (&["FT.TAGVALS", "idx", "tag"], "FT.TAGVALS", false),
            (&["FT.DICTADD", "dict", "term"], "FT.DICT", false),
            (&["FT.SPELLCHECK", "idx", "term"], "FT.SPELLCHECK", false),
            (&["FT.SUGADD", "key", "term", "1"], "FT.SUG", false),
            (&["FT.SYNUPDATE", "idx", "grp", "term"], "FT.SYN", false),
            (&["LPUSHX", "list", "v"], "LPUSHX", true),
            (&["RPUSHX", "list", "v"], "RPUSHX", true),
            (&["DECR", "n"], "DECR", true),
            (&["INCR", "n"], "INCR", true),
            (&["INCRBYFLOAT", "n", "1.5"], "INCRBYFLOAT", true),
            (&["LSET", "list", "0", "v"], "LSET", true),
            (&["LTRIM", "list", "0", "-1"], "LTRIM", true),
            (&["SUNION", "a", "b"], "SUNION", false),
            (&["SUNIONSTORE", "dst", "a", "b"], "SUNIONSTORE", true),
            (&["BLMPOP", "0", "1", "list", "LEFT"], "BLMPOP", true),
            (&["BZMPOP", "0", "1", "z", "MIN"], "BZMPOP", true),
            (&["BZPOPMAX", "z", "0"], "BZPOPMAX", true),
            (&["BZPOPMIN", "z", "0"], "BZPOPMIN", true),
            (&["ZCOUNT", "z", "-inf", "+inf"], "ZCOUNT", false),
            (&["ZADD", "z", "1", "a"], "ZADD", true),
            (&["ZDIFF", "1", "z"], "ZDIFF", false),
            (&["ZDIFFSTORE", "dst", "1", "z"], "ZDIFFSTORE", true),
            (&["ZINCRBY", "z", "1", "a"], "ZINCRBY", true),
            (&["ZINTER", "1", "z"], "ZINTER", false),
            (&["ZINTERCARD", "1", "z"], "ZINTERCARD", false),
            (&["ZINTERSTORE", "dst", "1", "z"], "ZINTERSTORE", true),
            (&["ZLEXCOUNT", "z", "-", "+"], "ZLEXCOUNT", false),
            (&["ZMPOP", "1", "z", "MIN"], "ZMPOP", true),
            (&["ZSCORE", "z", "a"], "ZSCORE", false),
            (&["ZCARD", "z"], "ZCARD", false),
            (&["ZPOPMAX", "z"], "ZPOPMAX", true),
            (&["ZPOPMIN", "z"], "ZPOPMIN", true),
            (&["ZRANDMEMBER", "z"], "ZRANDMEMBER", false),
            (&["ZRANK", "z", "a"], "ZRANK", false),
            (&["ZREM", "z", "a"], "ZREM", true),
            (&["ZREMRANGEBYLEX", "z", "-", "+"], "ZREMRANGEBYLEX", true),
            (&["ZREMRANGEBYRANK", "z", "0", "1"], "ZREMRANGEBYRANK", true),
            (
                &["ZREMRANGEBYSCORE", "z", "-inf", "+inf"],
                "ZREMRANGEBYSCORE",
                true,
            ),
            (&["ZRANGE", "z", "0", "-1"], "ZRANGE", false),
            (&["ZRANGEBYLEX", "z", "-", "+"], "ZRANGEBYLEX", false),
            (&["ZRANGESTORE", "dst", "z", "0", "-1"], "ZRANGESTORE", true),
            (&["ZREVRANGE", "z", "0", "-1"], "ZREVRANGE", false),
            (&["ZREVRANGEBYLEX", "z", "+", "-"], "ZREVRANGEBYLEX", false),
            (
                &["ZREVRANGEBYSCORE", "z", "+inf", "-inf"],
                "ZREVRANGEBYSCORE",
                false,
            ),
            (&["ZREVRANK", "z", "a"], "ZREVRANK", false),
            (
                &["ZRANGEBYSCORE", "z", "-inf", "+inf"],
                "ZRANGEBYSCORE",
                false,
            ),
            (&["ZSCAN", "z", "0"], "ZSCAN", false),
            (&["ZMSCORE", "z", "a"], "ZMSCORE", false),
            (&["ZUNION", "1", "z"], "ZUNION", false),
            (&["ZUNIONSTORE", "dst", "1", "z"], "ZUNIONSTORE", true),
            (&["XADD", "s", "*", "f", "v"], "XADD", true),
            (&["XACK", "s", "g", "1-0"], "XACK", true),
            (&["XACKDEL", "s", "g", "1-0"], "XACKDEL", true),
            (
                &["XAUTOCLAIM", "s", "g", "c", "0", "0-0"],
                "XAUTOCLAIM",
                true,
            ),
            (&["XCFGSET", "s", "MAX-DELETED-ID", "0-0"], "XCFGSET", false),
            (&["XCLAIM", "s", "g", "c", "0", "1-0"], "XCLAIM", true),
            (&["XDEL", "s", "1-0"], "XDEL", true),
            (&["XDELEX", "s", "1-0"], "XDELEX", true),
            (&["XGROUP", "CREATE", "s", "g", "$"], "XGROUP", true),
            (&["XINFO", "STREAM", "s"], "XINFO", false),
            (&["XLEN", "s"], "XLEN", false),
            (&["XPENDING", "s", "g"], "XPENDING", false),
            (&["XRANGE", "s", "-", "+"], "XRANGE", false),
            (&["XREAD", "STREAMS", "s", "0-0"], "XREAD", false),
            (
                &["XREADGROUP", "GROUP", "g", "c", "STREAMS", "s", ">"],
                "XREADGROUP",
                true,
            ),
            (&["XREVRANGE", "s", "+", "-"], "XREVRANGE", false),
            (&["XSETID", "s", "0-0"], "XSETID", true),
            (&["XTRIM", "s", "MAXLEN", "10"], "XTRIM", true),
            (&["DECRBY", "n", "2"], "DECRBY", true),
            (&["ECHO", "hello"], "ECHO", false),
            (&["EXPIREAT", "k", "1"], "EXPIREAT", true),
            (&["RANDOMKEY"], "RANDOMKEY", false),
            (&["PEXPIREAT", "k", "1"], "PEXPIREAT", true),
            (&["PEXPIRETIME", "k"], "PEXPIRETIME", false),
            (&["PEXPIRE", "k", "1"], "PEXPIRE", true),
            (&["PSETEX", "k", "1", "v"], "PSETEX", true),
            (&["LRANGE", "list", "0", "-1"], "LRANGE", false),
            (&["BGSAVE"], "BGSAVE", false),
            (&["SAVE"], "SAVE", false),
            (&["GETSET", "k", "v"], "GETSET", true),
            (&["INFO"], "INFO", false),
            (&["MOVE", "k", "1"], "MOVE", true),
            (&["SMISMEMBER", "s", "a"], "SMISMEMBER", false),
            (&["SRANDMEMBER", "s"], "SRANDMEMBER", false),
            (&["SSCAN", "s", "0"], "SSCAN", false),
            (&["TOUCH", "k"], "TOUCH", false),
            (&["UNLINK", "k"], "UNLINK", true),
            (&["MULTI"], "MULTI", false),
            (&["DISCARD"], "DISCARD", false),
            (&["EXEC"], "EXEC", false),
            (&["WATCH", "k"], "WATCH", false),
            (&["UNWATCH"], "UNWATCH", false),
            (&["VADD", "v", "VALUES", "2", "1", "0", "m"], "VADD", true),
            (&["VSIM", "v", "VALUES", "2", "1", "0"], "VSIM", false),
            (&["VREM", "v", "m"], "VREM", true),
            (&["VCARD", "v"], "VCARD", false),
            (&["VDIM", "v"], "VDIM", false),
            (&["VEMB", "v", "m"], "VEMB", false),
            (&["VGETATTR", "v", "m"], "VGETATTR", false),
            (&["VSETATTR", "v", "m", "{}"], "VSETATTR", true),
            (&["VINFO", "v"], "VINFO", false),
            (&["VRANDMEMBER", "v"], "VRANDMEMBER", false),
            (&["VLINKS", "v", "m"], "VLINKS", false),
            (&["JSON.SET", "j", "$", "{}"], "JSON.SET", true),
            (&["JSON.GET", "j"], "JSON.GET", false),
            (&["JSON.DEL", "j"], "JSON.DEL", true),
            (&["JSON.TYPE", "j"], "JSON.TYPE", false),
            (&["EVAL", "return 1", "0"], "LUA", true),
            (&["WASM.LIST"], "WASM", false),
        ];

        for (args, expected_name, expected_aof) in cases {
            let command = Command::parse_from_frame(frame_args(args))
                .unwrap_or_else(|err| panic!("{args:?} failed to parse: {err}"));
            assert_eq!(command.name(), *expected_name, "{args:?}");
            assert_eq!(command.propagate_aof_if_needed(), *expected_aof, "{args:?}");
        }

        let unsupported = Command::FtUnsupported(
            FtUnsupported::parse_from_frame(frame_args(&["FT.DEBUG", "idx"])).unwrap(),
        );
        assert_eq!(unsupported.name(), "FT.UNSUPPORTED");
        assert!(!unsupported.propagate_aof_if_needed());

        let unknown = Command::parse_from_frame(frame_args(&["NOTACOMMAND"])).unwrap();
        assert_eq!(unknown.name(), "UNKNOWN");
        assert!(!unknown.propagate_aof_if_needed());
    }
}
