impl Command {
    pub fn parse_from_frame(frame: Frame) -> Result<Self, Error> {
        let command_name = frame
            .get_arg(0)
            .ok_or_else(|| Error::msg("ERR empty command"))?;
        let command = match command_name.to_uppercase().as_str() {
            "AUTH" => Command::Auth(Auth::parse_from_frame(frame)?),
            "BITCOUNT" => Command::Bitcount(Bitcount::parse_from_frame(frame)?),
            "BITFIELD" => Command::Bitfield(Bitfield::parse_from_frame(frame)?),
            "BITFIELD_RO" => Command::Bitfield(Bitfield::parse_ro_from_frame(frame)?),
            "BITOP" => Command::Bitop(Bitop::parse_from_frame(frame)?),
            "BITPOS" => Command::Bitpos(Bitpos::parse_from_frame(frame)?),
            "COPY" => Command::Copy(Copy::parse_from_frame(frame)?),
            "DEL" => Command::Del(Del::parse_from_frame(frame)?),
            "EXPIRE" => Command::Expire(Expire::parse_from_frame(frame)?),
            "EXPIRETIME" => Command::ExpireTime(ExpireTime::parse_from_frame(frame)?),
            "FLUSHALL" => Command::Flushall(Flushall::parse_from_frame(frame)?),
            "FLUSHDB" => Command::Flushdb(Flushdb::parse_from_frame(frame)?),
            "FT.CREATE" => Command::FtCreate(FtCreate::parse_from_frame(frame)?),
            "FT._LIST" => Command::FtList(FtList::parse_from_frame(frame)?),
            "FT.DROPINDEX" => Command::FtDropIndex(FtDropIndex::parse_from_frame(frame)?),
            "FT.ALTER" => Command::FtAlter(FtAlter::parse_from_frame(frame)?),
            "FT.ALIASADD" => Command::FtAliasAdd(FtAliasAdd::parse_from_frame(frame)?),
            "FT.ALIASUPDATE" => Command::FtAliasUpdate(FtAliasUpdate::parse_from_frame(frame)?),
            "FT.ALIASDEL" => Command::FtAliasDel(FtAliasDel::parse_from_frame(frame)?),
            "FT.CONFIG" => Command::FtConfig(FtConfig::parse_from_frame(frame)?),
            "FT.INFO" => Command::FtInfo(FtInfo::parse_from_frame(frame)?),
            "FT.SEARCH" => Command::FtSearch(FtSearch::parse_from_frame(frame)?),
            "FT.HYBRID" => Command::FtHybrid(FtHybrid::parse_from_frame(frame)?),
            "FT.AGGREGATE" => Command::FtAggregate(FtAggregate::parse_from_frame(frame)?),
            "FT.CURSOR" => Command::FtCursor(FtCursor::parse_from_frame(frame)?),
            "FT.PROFILE" => Command::FtProfile(FtProfile::parse_from_frame(frame)?),
            "FT.EXPLAIN" | "FT.EXPLAINCLI" => {
                Command::FtExplain(FtExplain::parse_from_frame(frame)?)
            }
            "FT.TAGVALS" => Command::FtTagVals(FtTagVals::parse_from_frame(frame)?),
            "FT.DICTADD" | "FT.DICTDEL" | "FT.DICTDUMP" => {
                Command::FtDict(FtDict::parse_from_frame(frame)?)
            }
            "FT.SPELLCHECK" => Command::FtSpellCheck(FtSpellCheck::parse_from_frame(frame)?),
            "FT.SUGADD" | "FT.SUGDEL" | "FT.SUGGET" | "FT.SUGLEN" => {
                Command::FtSug(FtSug::parse_from_frame(frame)?)
            }
            "FT.SYNDUMP" | "FT.SYNUPDATE" => Command::FtSyn(FtSyn::parse_from_frame(frame)?),
            "GETRANGE" | "SUBSTR" => Command::GetRange(GetRange::parse_from_frame(frame)?),
            "GETDEL" => Command::GetDel(GetDel::parse_from_frame(frame)?),
            "GETEX" => Command::GetEx(GetEx::parse_from_frame(frame)?),
            "GET" => Command::Get(Get::parse_from_frame(frame)?),
            "LCS" => Command::Lcs(Lcs::parse_from_frame(frame)?),
            "GEOADD" => Command::Geoadd(Geoadd::parse_from_frame(frame)?),
            "GEODIST" => Command::Geodist(Geodist::parse_from_frame(frame)?),
            "GEOHASH" => Command::Geohash(Geohash::parse_from_frame(frame)?),
            "GEOPOS" => Command::Geopos(Geopos::parse_from_frame(frame)?),
            "GEORADIUS" | "GEORADIUS_RO" => {
                Command::Georadius(Geosearch::parse_georadius_from_frame(frame)?)
            }
            "GEORADIUSBYMEMBER" | "GEORADIUSBYMEMBER_RO" => {
                Command::Georadiusbymember(Geosearch::parse_georadiusbymember_from_frame(frame)?)
            }
            "GEOSEARCH" => Command::Geosearch(Geosearch::parse_from_frame(frame)?),
            "GEOSEARCHSTORE" => Command::Geosearchstore(Geosearchstore::parse_from_frame(frame)?),
            "GETBIT" => Command::Getbit(Getbit::parse_from_frame(frame)?),
            "PING" => Command::Ping(Ping::parse_from_frame(frame)?),
            "PFADD" => Command::Pfadd(Pfadd::parse_from_frame(frame)?),
            "PFCOUNT" => Command::Pfcount(Pfcount::parse_from_frame(frame)?),
            "PFMERGE" => Command::Pfmerge(Pfmerge::parse_from_frame(frame)?),
            "PTTL" => Command::Pttl(Pttl::parse_from_frame(frame)?),
            "TYPE" => Command::Type(Type::parse_from_frame(frame)?),
            "SELECT" => Command::Select(Select::parse_from_frame(frame)?),
            "SET" => Command::Set(Set::parse_from_frame(frame)?),
            "SETBIT" => Command::Setbit(Setbit::parse_from_frame(frame)?),
            "SETEX" => Command::Setex(Setex::parse_from_frame(frame)?),
            "SETNX" => Command::Setnx(Setnx::parse_from_frame(frame)?),
            "SETRANGE" => Command::SetRange(SetRange::parse_from_frame(frame)?),
            "TTL" => Command::Ttl(Ttl::parse_from_frame(frame)?),
            "RANDOMKEY" => Command::RandomKey(RandomKey::parse_from_frame(frame)?),
            "RENAME" => Command::Rename(Rename::parse_from_frame(frame)?),
            "EXISTS" => Command::Exists(Exists::parse_from_frame(frame)?),
            "STRLEN" => Command::Strlen(Strlen::parse_from_frame(frame)?),
            "MSET" => Command::Mset(Mset::parse_from_frame(frame)?),
            "MSETEX" => Command::Msetex(Msetex::parse_from_frame(frame)?),
            "MSETNX" => Command::Msetnx(Msetnx::parse_from_frame(frame)?),
            "MGET" => Command::Mget(Mget::parse_from_frame(frame)?),
            "APPEND" => Command::Append(Append::parse_from_frame(frame)?),
            "DBSIZE" => Command::Dbsize(Dbsize::parse_from_frame(frame)?),
            "HSET" => Command::Hset(Hset::parse_from_frame(frame)?),
            "HEXPIRE" => Command::Hexpire(Hexpire::parse_from_frame(frame, false, false)?),
            "HEXPIREAT" => Command::HexpireAt(Hexpire::parse_from_frame(frame, false, true)?),
            "HEXPIRETIME" => Command::HexpireTime(Httl::parse_from_frame(frame, false, true)?),
            "HGET" => Command::Hget(Hget::parse_from_frame(frame)?),
            "HGETDEL" => Command::Hgetdel(Hgetdel::parse_from_frame(frame)?),
            "HGETEX" => Command::Hgetex(Hgetex::parse_from_frame(frame)?),
            "HINCRBY" => Command::Hincrby(Hincrby::parse_from_frame(frame)?),
            "HINCRBYFLOAT" => Command::HincrbyFloat(HincrbyFloat::parse_from_frame(frame)?),
            "HMSET" => Command::Hmset(Hmset::parse_from_frame(frame)?),
            "HPERSIST" => Command::Hpersist(Hpersist::parse_from_frame(frame)?),
            "HPEXPIRE" => Command::Hpexpire(Hexpire::parse_from_frame(frame, true, false)?),
            "HPEXPIREAT" => Command::HpexpireAt(Hexpire::parse_from_frame(frame, true, true)?),
            "HPEXPIRETIME" => Command::HpexpireTime(Httl::parse_from_frame(frame, true, true)?),
            "HPTTL" => Command::Hpttl(Httl::parse_from_frame(frame, true, false)?),
            "HDEL" => Command::Hdel(Hdel::parse_from_frame(frame)?),
            "HEXISTS" => Command::Hexists(Hexists::parse_from_frame(frame)?),
            "HSTRLEN" => Command::Hstrlen(Hstrlen::parse_from_frame(frame)?),
            "KEYS" => Command::Keys(Keys::parse_from_frame(frame)?),
            "HMGET" => Command::Hmget(Hmget::parse_from_frame(frame)?),
            "HLEN" => Command::Hlen(Hlen::parse_from_frame(frame)?),
            "HSCAN" => Command::Hscan(Hscan::parse_from_frame(frame)?),
            "HRANDFIELD" => Command::Hrandfield(Hrandfield::parse_from_frame(frame)?),
            "HGETALL" => Command::Hgetall(Hgetall::parse_from_frame(frame)?),
            "HSETEX" => Command::Hsetex(Hsetex::parse_from_frame(frame)?),
            "HSETNX" => Command::Hsetnx(Hsetnx::parse_from_frame(frame)?),
            "HTTL" => Command::Httl(Httl::parse_from_frame(frame, false, false)?),
            "HKEYS" => Command::Hkeys(Hkeys::parse_from_frame(frame)?),
            "BLMOVE" => Command::Blmove(Blmove::parse_from_frame(frame)?),
            "BLMPOP" => Command::Blmpop(Blmpop::parse_from_frame(frame)?),
            "BLPOP" => Command::Blpop(Blpop::parse_from_frame(frame)?),
            "BRPOP" => Command::Brpop(Brpop::parse_from_frame(frame)?),
            "BRPOPLPUSH" => Command::Brpoplpush(Brpoplpush::parse_from_frame(frame)?),
            "PERSIST" => Command::Persist(Persist::parse_from_frame(frame)?),
            "LINDEX" => Command::Lindex(Lindex::parse_from_frame(frame)?),
            "LINSERT" => Command::Linsert(Linsert::parse_from_frame(frame)?),
            "LMOVE" => Command::Lmove(Lmove::parse_from_frame(frame)?),
            "RPOP" => Command::Rpop(Rpop::parse_from_frame(frame)?),
            "RPOPLPUSH" => Command::Rpoplpush(Rpoplpush::parse_from_frame(frame)?),
            "LPOP" => Command::Lpop(Lpop::parse_from_frame(frame)?),
            "LPOS" => Command::Lpos(Lpos::parse_from_frame(frame)?),
            "LREM" => Command::Lrem(Lrem::parse_from_frame(frame)?),
            "LLEN" => Command::Llen(Llen::parse_from_frame(frame)?),
            "HVALS" => Command::Hvals(Hvals::parse_from_frame(frame)?),
            "RPUSH" => Command::Rpush(Rpush::parse_from_frame(frame)?),
            "LMPOP" => Command::Lmpop(Lmpop::parse_from_frame(frame)?),
            "LPUSH" => Command::Lpush(Lpush::parse_from_frame(frame)?),
            "SADD" => Command::Sadd(Sadd::parse_from_frame(frame)?),
            "SCARD" => Command::Scard(Scard::parse_from_frame(frame)?),
            "RENAMENX" => Command::Renamenx(Renamenx::parse_from_frame(frame)?),
            "EXPIREAT" => Command::ExpireAt(ExpireAt::parse_from_frame(frame)?),
            "SUNIONSTORE" => Command::Sunionstore(Sunionstore::parse_from_frame(frame)?),
            "SISMEMBER" => Command::Sismember(Sismember::parse_from_frame(frame)?),
            "SMEMBERS" => Command::Smembers(Smembers::parse_from_frame(frame)?),
            "SPOP" => Command::Spop(Spop::parse_from_frame(frame)?),
            "SREM" => Command::Srem(Srem::parse_from_frame(frame)?),
            "LPUSHX" => Command::Lpushx(Lpushx::parse_from_frame(frame)?),
            "RPUSHX" => Command::Rpushx(Rpushx::parse_from_frame(frame)?),
            "INCR" => Command::Incr(Incr::parse_from_frame(frame)?),
            "DECR" => Command::Decr(Decr::parse_from_frame(frame)?),
            "LSET" => Command::Lset(Lset::parse_from_frame(frame)?),
            "LTRIM" => Command::Ltrim(Ltrim::parse_from_frame(frame)?),
            "SUNION" => Command::Sunion(Sunion::parse_from_frame(frame)?),
            "BZMPOP" => Command::Bzmpop(Bzmpop::parse_from_frame(frame)?),
            "BZPOPMAX" => Command::Bzpopmax(Bzpopmax::parse_from_frame(frame)?),
            "BZPOPMIN" => Command::Bzpopmin(Bzpopmin::parse_from_frame(frame)?),
            "ZCOUNT" => Command::Zcount(Zcount::parse_from_frame(frame)?),
            "ZADD" => Command::Zadd(Zadd::parse_from_frame(frame)?),
            "ZDIFF" => Command::Zdiff(Zdiff::parse_from_frame(frame)?),
            "ZDIFFSTORE" => Command::Zdiffstore(Zdiffstore::parse_from_frame(frame)?),
            "ZCARD" => Command::Zcard(Zcard::parse_from_frame(frame)?),
            "ZINTER" => Command::Zinter(Zinter::parse_from_frame(frame)?),
            "ZINTERCARD" => Command::Zintercard(Zintercard::parse_from_frame(frame)?),
            "ZINTERSTORE" => Command::Zinterstore(Zinterstore::parse_from_frame(frame)?),
            "ZLEXCOUNT" => Command::Zlexcount(Zlexcount::parse_from_frame(frame)?),
            "ZMPOP" => Command::Zmpop(Zmpop::parse_from_frame(frame)?),
            "ZPOPMAX" => Command::Zpopmax(Zpopmax::parse_from_frame(frame)?),
            "ZPOPMIN" => Command::Zpopmin(Zpopmin::parse_from_frame(frame)?),
            "ZRANDMEMBER" => Command::Zrandmember(Zrandmember::parse_from_frame(frame)?),
            "ZSCORE" => Command::Zscore(Zscore::parse_from_frame(frame)?),
            "ZREM" => Command::Zrem(Zrem::parse_from_frame(frame)?),
            "ZREMRANGEBYLEX" => Command::Zremrangebylex(Zremrangebylex::parse_from_frame(frame)?),
            "ZREMRANGEBYRANK" => {
                Command::Zremrangebyrank(Zremrangebyrank::parse_from_frame(frame)?)
            }
            "ZREMRANGEBYSCORE" => {
                Command::Zremrangebyscore(Zremrangebyscore::parse_from_frame(frame)?)
            }
            "ZRANGE" => Command::Zrange(Zrange::parse_from_frame(frame)?),
            "ZRANGEBYLEX" => Command::Zrangebylex(Zrangebylex::parse_from_frame(frame)?),
            "ZREVRANGE" => Command::Zrevrange(Zrevrange::parse_from_frame(frame)?),
            "ZREVRANGEBYLEX" => Command::Zrevrangebylex(Zrevrangebylex::parse_from_frame(frame)?),
            "ZREVRANGEBYSCORE" => {
                Command::Zrevrangebyscore(Zrevrangebyscore::parse_from_frame(frame)?)
            }
            "ZREVRANK" => Command::Zrevrank(Zrevrank::parse_from_frame(frame)?),
            "ZRANGEBYSCORE" => Command::Zrangebyscore(Zrangebyscore::parse_from_frame(frame)?),
            "ZRANGESTORE" => Command::Zrangestore(Zrangestore::parse_from_frame(frame)?),
            "ZMSCORE" => Command::Zmscore(Zmscore::parse_from_frame(frame)?),
            "ZUNION" => Command::Zunion(Zunion::parse_from_frame(frame)?),
            "ZUNIONSTORE" => Command::Zunionstore(Zunionstore::parse_from_frame(frame)?),
            "SDIFF" => Command::Sdiff(Sdiff::parse_from_frame(frame)?),
            "SDIFFSTORE" => Command::Sdiffstore(Sdiffstore::parse_from_frame(frame)?),
            "SINTER" => Command::Sinter(Sinter::parse_from_frame(frame)?),
            "SINTERCARD" => Command::Sintercard(Sintercard::parse_from_frame(frame)?),
            "SINTERSTORE" => Command::Sinterstore(Sinterstore::parse_from_frame(frame)?),
            "SMISMEMBER" => Command::Smismember(Smismember::parse_from_frame(frame)?),
            "SMOVE" => Command::Smove(Smove::parse_from_frame(frame)?),
            "SRANDMEMBER" => Command::Srandmember(Srandmember::parse_from_frame(frame)?),
            "ZRANK" => Command::Zrank(Zrank::parse_from_frame(frame)?),
            "ZINCRBY" => Command::Zincrby(Zincrby::parse_from_frame(frame)?),
            "INCRBY" => Command::Incrby(Incrby::parse_from_frame(frame)?),
            "INCRBYFLOAT" => Command::IncrbyFloat(IncrbyFloat::parse_from_frame(frame)?),
            "DECRBY" => Command::Decrby(Decrby::parse_from_frame(frame)?),
            "ECHO" => Command::Echo(Echo::parse_from_frame(frame)?),
            "PEXPIRE" => Command::Pexpire(Pexpire::parse_from_frame(frame)?),
            "PSETEX" => Command::Psetex(Psetex::parse_from_frame(frame)?),
            "PEXPIREAT" => Command::PexpireAt(PexpireAt::parse_from_frame(frame)?),
            "PEXPIRETIME" => Command::PexpireTime(PexpireTime::parse_from_frame(frame)?),
            "LRANGE" => Command::Lrange(Lrange::parse_from_frame(frame)?),
            "GETSET" => Command::GetSet(GetSet::parse_from_frame(frame)?),
            "CLIENT" => Command::Client(Client::parse_from_frame(frame)?),
            "CONFIG" => Command::Config(Config::parse_from_frame(frame)?),
            "INFO" => Command::Info(Info::parse_from_frame(frame)?),
            "BGSAVE" => Command::Bgsave(Bgsave::parse_from_frame(frame)?),
            "SAVE" => Command::Save(Save::parse_from_frame(frame)?),
            "MOVE" => Command::Move(Move::parse_from_frame(frame)?),
            "MULTI" => Command::Multi(Multi::parse_from_frame(frame)?),
            "EXEC" => Command::Exec(Exec::parse_from_frame(frame)?),
            "DISCARD" => Command::Discard(Discard::parse_from_frame(frame)?),
            "WATCH" => Command::Watch(Watch::parse_from_frame(frame)?),
            "UNWATCH" => Command::Unwatch(Unwatch::parse_from_frame(frame)?),
            "SCAN" => Command::Scan(Scan::parse_from_frame(frame)?),
            "SSCAN" => Command::Sscan(Sscan::parse_from_frame(frame)?),
            "ZSCAN" => Command::Zscan(Zscan::parse_from_frame(frame)?),
            "XACK" => Command::Xack(Xack::parse_from_frame(frame)?),
            "XACKDEL" => Command::Xackdel(Xackdel::parse_from_frame(frame)?),
            "XADD" => Command::Xadd(Xadd::parse_from_frame(frame)?),
            "XAUTOCLAIM" => Command::Xautoclaim(Xautoclaim::parse_from_frame(frame)?),
            "XCFGSET" => Command::Xcfgset(Xcfgset::parse_from_frame(frame)?),
            "XCLAIM" => Command::Xclaim(Xclaim::parse_from_frame(frame)?),
            "XDEL" => Command::Xdel(Xdel::parse_from_frame(frame)?),
            "XDELEX" => Command::Xdelex(Xdelex::parse_from_frame(frame)?),
            "XGROUP" => Command::Xgroup(Xgroup::parse_from_frame(frame)?),
            "XINFO" => Command::Xinfo(Xinfo::parse_from_frame(frame)?),
            "XLEN" => Command::Xlen(Xlen::parse_from_frame(frame)?),
            "XPENDING" => Command::Xpending(Xpending::parse_from_frame(frame)?),
            "XRANGE" => Command::Xrange(Xrange::parse_from_frame(frame)?),
            "XREAD" => Command::Xread(Xread::parse_from_frame(frame)?),
            "XREADGROUP" => Command::Xreadgroup(Xreadgroup::parse_from_frame(frame)?),
            "XREVRANGE" => Command::Xrevrange(Xrevrange::parse_from_frame(frame)?),
            "XSETID" => Command::Xsetid(Xsetid::parse_from_frame(frame)?),
            "XTRIM" => Command::Xtrim(Xtrim::parse_from_frame(frame)?),
            "TOUCH" => Command::Touch(Touch::parse_from_frame(frame)?),
            "UNLINK" => Command::Unlink(Unlink::parse_from_frame(frame)?),
            "JSON.SET" => Command::JsonSet(JsonSet::parse_from_frame(frame)?),
            "JSON.GET" => Command::JsonGet(JsonGet::parse_from_frame(frame)?),
            "JSON.DEL" => Command::JsonDel(JsonDel::parse_from_frame(frame)?),
            "JSON.TYPE" => Command::JsonType(JsonType::parse_from_frame(frame)?),
            "VADD" => Command::VAdd(VAdd::parse_from_frame(frame)?),
            "VSIM" => Command::VSim(VSim::parse_from_frame(frame)?),
            "VREM" => Command::VRem(VRem::parse_from_frame(frame)?),
            "VCARD" => Command::VCard(VCard::parse_from_frame(frame)?),
            "VDIM" => Command::VDim(VDim::parse_from_frame(frame)?),
            "VEMB" => Command::VEmb(VEmb::parse_from_frame(frame)?),
            "VGETATTR" => Command::VGetAttr(VGetAttr::parse_from_frame(frame)?),
            "VSETATTR" => Command::VSetAttr(VSetAttr::parse_from_frame(frame)?),
            "VINFO" => Command::VInfo(VInfo::parse_from_frame(frame)?),
            "VRANDMEMBER" => Command::VRandMember(VRandMember::parse_from_frame(frame)?),
            "VLINKS" => Command::VLinks(VLinks::parse_from_frame(frame)?),
            "EVAL" | "EVALSHA" | "EVAL_RO" | "EVALSHA_RO" | "SCRIPT" => {
                Command::Lua(LuaCommand::parse_from_frame(frame)?)
            }
            "WASM.LOAD" | "WASM.CALL" | "WASM.CALL_RO" | "WASM.DEL" | "WASM.SCAN" | "WASM.LIST"
            | "FUNCTION" | "FCALL" | "FCALL_RO" => {
                Command::Wasm(WasmCommand::parse_from_frame(frame)?)
            }
            _ => Command::Unknown(Unknown::parse_from_frame(frame)?),
        };
        Ok(command)
    }
}
